### PR TITLE
Gracefully handle extended sessions for out-of-proc languages

### LINKED ISSUE #1452: Handle extended sessions "gracefully" with out-of-proc languages
Currently, if using extended sessions with any non-.NET language, the customer's orchestrations will silently not execute as expected. This is very undesirable behavior, so it is preferable to do one of the following instead:

1. Log a warning that extended sessions is true, but that we will use extended sessions = false instead.
2. Throw an exception on functions host startup, so that we fail fast and it is apparent to the customer they are in an unsupported scenario.

### PR DESCRIPTION
**Pull request by ConnorMcMahon**
Currently, when extended sessions is set to true for out-of-proc
languages, orchestrations will silently fail. Now, if we detect
out-of-proc languages when extended sessions are true, we emit a warning
and set extended sessions to false.

Fixes #1452.

### CODE REVIEW

File: src/WebJobs.Extensions.DurableTask/Options/DurableTaskOptions.cs [hunk 1]
```diff
@@ -271,6 +271,17 @@ internal void Validate()
                     "See documentation on Task Hubs for information on how to set this: https://docs.microsoft.com/azure/azure-functions/durable/durable-functions-task-hubs");
             }
 
+            string runtimeLanguage = environmentVariableResolver.Resolve("FUNCTIONS_WORKER_RUNTIME");
+            if (!string.Equals(runtimeLanguage, "dotnet", StringComparison.OrdinalIgnoreCase))
```
Comment (cgillum) [inline src/WebJobs.Extensions.DurableTask/Options/DurableTaskOptions.cs:275]: Shouldn't we also be checking if `this.ExtendedSessionsEnabled == true`? Otherwise, won't we always log this for every non-.NET function app even if they set it to false?

**Review by cgillum — CHANGES_REQUESTED** [review]

File: src/WebJobs.Extensions.DurableTask/Options/DurableTaskOptions.cs (hunk 1 above)
Comment (ConnorMcMahon) [reply src/WebJobs.Extensions.DurableTask/Options/DurableTaskOptions.cs:275]: Ah, good catch!

Comment (cgillum) [reply src/WebJobs.Extensions.DurableTask/Options/DurableTaskOptions.cs:275]: Also, should we consider the case where this environment variable is not set at all? There are many .NET apps which don't set this environment variable, and I'm worried that we'd be inadvertently disabling extended sessions for those apps that upgrade to this extension version.

File: src/WebJobs.Extensions.DurableTask/Options/DurableTaskOptions.cs [hunk 2]
```diff
@@ -271,6 +271,18 @@ internal void Validate()
                     "See documentation on Task Hubs for information on how to set this: https://docs.microsoft.com/azure/azure-functions/durable/durable-functions-task-hubs");
             }
 
+            string runtimeLanguage = environmentVariableResolver.Resolve("FUNCTIONS_WORKER_RUNTIME");
+            if (this.ExtendedSessionsEnabled &&
+                !string.Equals(runtimeLanguage, "dotnet", StringComparison.OrdinalIgnoreCase))
```
Comment (cgillum) [inline src/WebJobs.Extensions.DurableTask/Options/DurableTaskOptions.cs:276]: GitHub doesn't always show review comment threads the way I expect, so I'll post this comment again for this latest iteration:

> Also, should we consider the case where this environment variable is not set at all? There are many .NET apps which don't set this environment variable, and I'm worried that we'd be inadvertently disabling extended sessions for those apps that upgrade to this extension version.

**Review by cgillum — CHANGES_REQUESTED** [review]

File: src/WebJobs.Extensions.DurableTask/Options/DurableTaskOptions.cs (hunk 2 above)
Comment (ConnorMcMahon) [reply src/WebJobs.Extensions.DurableTask/Options/DurableTaskOptions.cs:277]: I'm going to add a test for this case too.

**Review by davidmrdavid — APPROVED** [review]
Looks good to me!
My only request is for the `Validate` method to be updated with a header comment saying just what it is validating.

**Review by cgillum — APPROVED** [review]
LGTM - :shipit:
