### PR TITLE
Remove DurableClientContext, allow for direct binding of DurableTaskClient

### LINKED ISSUE #2240: CreateCheckStatusResponse returns wrong status code
### Description
According to the documentation [here](https://github.com/Azure/azure-functions-durable-extension/blob/d9a254ee4cc8f8cfbfb15eebff3c3f4a38b1e7de/src/Worker.Extensions.DurableTask/DurableClientContext.cs#L42)
```csharp
/// <returns>An HTTP 202 response with a Location header and a payload containing instance control URLs.</returns>
```
and [here](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-http-features?tabs=csharp#async-operation-tracking)
> The target HTTP trigger returns an HTTP 202 response with a Location header that has the value "statusQueryGetUri".

`CreateCheckStatusResponse` should return a 202 (Accepted) status code.

However, the [`DefaultDurableClientContext`](https://github.com/Azure/azure-functions-durable-extension/blob/d9a254ee4cc8f8cfbfb15eebff3c3f4a38b1e7de/src/Worker.Extensions.DurableTask/DefaultDurableClientContext.cs#L52) creates a response with status code 201 (Created):
```csharp
HttpResponseData response = request.CreateResponse(HttpStatusCode.Created);
```

### Expected behavior
The response created by `CreateCheckStatusResponse` should have a status code of 202 (Accepted).

### Actual behavior
The response has a status code of 201 (Created).

### Known workarounds
You can overwrite the status code manually:
```csharp
response.StatusCode = HttpStatusCode.Accepted;
```

### App Details

- **Microsoft.Azure.Functions.Worker**: 1.8.0
- **Microsoft.Azure.Functions.Worker.Extensions.DurableTask**: 0.4.1-beta
- **Azure Functions runtime version**: 4.x
- **Programming language used**: C#

### PR DESCRIPTION
**Pull request by jviau**
This PR removes `DurableClientContext`, instead allowing for direct binding to `DurableTaskClient` via `[DurableClient]` attribute. The HTTP methods on `DurableClientContext` were moved to extension methods for `DurableTaskClient`. The HTTP extension was also modified to (1) use `WorkerOptions.Serializer` and (2) be `202Accepted` by default to match the description.

### Issue describing the changes in this PR

resolves #2240

### Pull request checklist

* [x] My changes **do not** require documentation changes
    * [ ] Otherwise: Documentation PR is ready to merge and referenced in `pending_docs.md`
* [x] My changes **should not** be added to the release notes for the next release
    * [ ] Otherwise: I've added my notes to `release_notes.md`
* [x] My changes **do not** need to be backported to a previous version
    * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [x] I have added all required tests (Unit tests, E2E tests)
* [x] My changes **do not** require any extra work to be leveraged by OutOfProc SDKs
    * [ ] Otherwise: That work is being tracked here: #issue_or_pr_in_each_sdk
* [x] My changes **do not** change the version of the WebJobs.Extensions.DurableTask package
    * [ ] Otherwise: major or minor version updates are reflected in `/src/Worker.Extensions.DurableTask/AssemblyInfo.cs`

### CODE REVIEW

File: src/Worker.Extensions.DurableTask/DurableTaskClientExtensions.cs [hunk 1]
```diff
@@ -0,0 +1,109 @@
...
+    /// <param name="instanceId">The ID of the orchestration instance to check.</param>
+    /// <param name="statusCode">The status code.</param>
+    /// <param name="cancellation">The cancellation token.</param>
+    /// <returns>An HTTP response with a Location header and a payload containing instance control URLs.</returns>
+    public static HttpResponseData CreateCheckStatusResponse(
+        this DurableTaskClient client,
+        HttpRequestData request,
+        string instanceId,
+        HttpStatusCode statusCode,
+        CancellationToken cancellation = default)
```
Comment (cgillum) [inline src/Worker.Extensions.DurableTask/DurableTaskClientExtensions.cs:49]: Seems a little odd to pass a `CancellationToken` to a synchronous method that doesn't do any I/O, no?

File: src/Worker.Extensions.DurableTask/DurableTaskExtensionStartup.cs [hunk 2]
```diff
@@ -54,6 +54,7 @@ public override void Configure(IFunctionsWorkerApplicationBuilder applicationBui
             return new DurableTaskShimFactory(options, factory); // For GrpcOrchestrationRunner
         });
 
+        applicationBuilder.Services.Configure<WorkerOptions>(o => o.InputConverters.RegisterAt<DurableTaskClientConverter>(0));
```
Comment (cgillum) [inline src/Worker.Extensions.DurableTask/DurableTaskExtensionStartup.cs:57]: Is this step necessary? I thought the registration of input converters was done via the attribute?

**Review by cgillum — COMMENTED** [review]
I really like this change.

File: src/Worker.Extensions.DurableTask/DurableTaskClientExtensions.cs (hunk 1 above)
Comment (jviau) [reply src/Worker.Extensions.DurableTask/DurableTaskClientExtensions.cs:49]: It does do I/O though! It writes to the request stream. I took it in because the `ObjectSerializer.Serialize` method I use accepts it.

File: src/Worker.Extensions.DurableTask/DurableTaskExtensionStartup.cs (hunk 2 above)
Comment (jviau) [reply src/Worker.Extensions.DurableTask/DurableTaskExtensionStartup.cs:57]: Oh I need to remove that attribute haha. It doesn't work. Input binding attributes pointing to their input converter is not supported (yet).

File: src/Worker.Extensions.DurableTask/DurableTaskClientExtensions.cs (hunk 1 above)
Comment (cgillum) [reply src/Worker.Extensions.DurableTask/DurableTaskClientExtensions.cs:51]: Hmm, yeah, I guess so. It's weird that it's in synchronous code instead of async code, but I suppose that's because HTTP triggers in Azure Functions buffer the request and response streams? Anyways, doesn't hurt to have this, I guess, and maybe makes it more future-proof.

File: src/Worker.Extensions.DurableTask/DurableTaskExtensionStartup.cs (hunk 2 above)
Comment (cgillum) [reply src/Worker.Extensions.DurableTask/DurableTaskExtensionStartup.cs]: I see - yeah, I guess if it only works with the target class (which isn't doable in our case), then we should just remove that attribute.

**Review by cgillum — APPROVED** [review]
:shipit:
