### PR TITLE
Anaylzer: 0.3.1 bug fixes and small FunctionAnalyzer refactor

### LINKED ISSUE #1428: Analyzer: Null-ref exception when function returns nullable type
### Description
I'm seeing a `NullReferenceException` coming from the analyzer when I have an activity function that returns a nullable type. Below is an example code snippet that seems to trigger this:

### Relevant source code snippets
```csharp
    [FunctionName(nameof(Echo))]
    public static int? Echo([ActivityTrigger] int input)
    {
        return input;
    }
```

### Known workarounds
Using `Nullable<int>` instead of `int?` _seems_ to work as a workaround, though I had a hard time confirming:

```csharp
    [FunctionName(nameof(Echo))]
    public static Nullable<int> Echo([ActivityTrigger] int input)
    {
        return input;
    }
```

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 2.3.0
- **Azure Functions runtime version (1.0 or 2.0)**: 3.0
- **Analyzer version**: 0.3.0

### PR DESCRIPTION
**Pull request by amdeel**
Fixed NullReferenceException when using Nullable types in FunctionAnalyzer by adding a check for them. Added tests to cover Nullable types in ReturnTypeAnalyzerTests. resolves #1428

Fixed another ArgumentException related to SemanticModels. resovles #1457 

Added another error message in ArgumentAnalyzer when using null inputs for a value type. Added tests for this new check.

Refactored FunctionAnalyzer to get ITypeSymbols and store them in ActivityFunctionCall and ActivityFunctionDefinition so the child analyzers no longer have to get that information. Simplified some logic in ArgumentAnalyzer and ReturnTypeAnalyzer.

Incremented the version.

### CODE REVIEW

File: src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/ActivityFunction/FunctionAnalyzer.cs [hunk 1]
```diff
@@ -159,15 +166,77 @@ public void FindActivityFunction(SyntaxNodeAnalysisContext context)
...
+        }
+
+        private static bool TryGetDurableActivityContextExpression(SemanticModel semanticModel, SyntaxNode node, out SyntaxNode durableContextExpression)
+        {
+            if (SyntaxNodeUtils.TryGetMethodDeclaration(node, out SyntaxNode methodDeclaration))
+            {
+                var memberAccessExpressionList = methodDeclaration.DescendantNodes().Where(x => x.IsKind(SyntaxKind.SimpleMemberAccessExpression));
+                foreach (var memberAccessExpression in memberAccessExpressionList)
+                {
+                    var identifierName = memberAccessExpression.ChildNodes().Where(x => x.IsKind(SyntaxKind.IdentifierName)).FirstOrDefault();
```
Comment (ConnorMcMahon) [inline src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/ActivityFunction/FunctionAnalyzer.cs:223]: small nit: `.Where(predicate).FirstOrDefault()` can be replaced with `FirstOrDefault(predicate)`. 

Not a huge problem by any means, just keeps your linq queries a bit more brief.

File: src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/ActivityFunction/FunctionReturnTypeAnalyzer.cs [hunk 2]
```diff
@@ -31,33 +31,30 @@ public class FunctionReturnTypeAnalyzer
...
 
-            return SyntaxNodeUtils.IsMatchingDerivedOrCompatibleType(definitionReturnType, invocationReturnType);
+            return SyntaxNodeUtils.IsMatchingDerivedOrCompatibleType(definitionReturnType, invocation.ReturnType);
         }
 
         private static bool TryGetTaskTypeArgument(ITypeSymbol returnType, out ITypeSymbol taskTypeArgument)
         {
-            if (returnType.Name.Equals("Task") && returnType is INamedTypeSymbol namedType)
+            if (returnType != null && returnType.Name.Equals("Task") && returnType is INamedTypeSymbol namedType)
             {
```
Comment (ConnorMcMahon) [inline src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/ActivityFunction/FunctionReturnTypeAnalyzer.cs:58]: small nit: Could simplify to `if (returnType is INameTypSymbol namedType && namedType.Name.Equals("Task"))`.  You can do this because `is` does an implicit check for `null`.

File: src/WebJobs.Extensions.DurableTask.Analyzers/Resources.resx [hunk 3]
```diff
@@ -123,6 +123,9 @@
   <data name="ActivityArgumentAnalyzerMessageFormat" xml:space="preserve">
     <value>Activity function named '{0}' takes '{1}' but was given '{2}'.</value>
   </data>
+  <data name="ActivityArgumentAnalyzerMessageFormatInvalidNull" xml:space="preserve">
+    <value>Activity function named '{0}' takes '{1}' but was given null. Cannot pass null on a value type.</value>
```
Comment (ConnorMcMahon) [inline src/WebJobs.Extensions.DurableTask.Analyzers/Resources.resx:127]:
```suggestion
    <value>Activity function named '{0}' takes a parameter of type '{1}' but was given null. Cannot pass null on a value type.</value>
```

File: src/WebJobs.Extensions.DurableTask.Analyzers/SyntaxNodeUtils.cs [hunk 4]
```diff
@@ -27,28 +27,26 @@ public static DurableVersion GetDurableVersion(SemanticModel semanticModel)
             return (DurableVersion)version;
         }
 
-        public static SemanticModel GetSyntaxTreeSemanticModel(SemanticModel model, SyntaxNode node)
+        public static bool TryGetSemanticModelForSyntaxTree(SemanticModel model, SyntaxNode node, out SemanticModel newModel)
         {
-            if (model == null || node == null)
+            if (model == null || model.SyntaxTree == null || node == null || node.SyntaxTree == null)
```
Comment (ConnorMcMahon) [inline src/WebJobs.Extensions.DurableTask.Analyzers/SyntaxNodeUtils.cs:32]:
```suggestion
            if (model?.SyntaxTree == null || node?.SyntaxTree == null)
```

File: src/WebJobs.Extensions.DurableTask.Analyzers/SyntaxNodeUtils.cs [hunk 5]
```diff
@@ -113,7 +107,7 @@ internal static bool TryGetMethodReturnTypeNode(SyntaxNode node, out SyntaxNode
 
         private static bool TryGetChildTypeNode(SyntaxNode node, out SyntaxNode childTypeNode)
         {
-            childTypeNode = node.ChildNodes().Where(x => x.IsKind(SyntaxKind.IdentifierName) || x.IsKind(SyntaxKind.PredefinedType) || x.IsKind(SyntaxKind.GenericName) || x.IsKind(SyntaxKind.ArrayType) || x.IsKind(SyntaxKind.TupleType)).FirstOrDefault();
+            childTypeNode = node.ChildNodes().Where(x => x.IsKind(SyntaxKind.IdentifierName) || x.IsKind(SyntaxKind.PredefinedType) || x.IsKind(SyntaxKind.GenericName) || x.IsKind(SyntaxKind.ArrayType) || x.IsKind(SyntaxKind.TupleType) || x.IsKind(SyntaxKind.NullableType)).FirstOrDefault();
```
Comment (ConnorMcMahon) [inline src/WebJobs.Extensions.DurableTask.Analyzers/SyntaxNodeUtils.cs:110]: One line is starting to get hard to read.

```suggestion
            childTypeNode = node.ChildNodes()
                                .Where(
                                    x => x.IsKind(SyntaxKind.IdentifierName) 
                                    || x.IsKind(SyntaxKind.PredefinedType)
                                    || x.IsKind(SyntaxKind.GenericName)
                                    || x.IsKind(SyntaxKind.ArrayType)
                                    || x.IsKind(SyntaxKind.TupleType)
                                    || x.IsKind(SyntaxKind.NullableType))
                                .FirstOrDefault();
```

**Review by ConnorMcMahon — APPROVED** [review]
Looks good!

Just a few stylistic nits, and I would like a bit more clarification on the new warning message.

**Review by ConnorMcMahon — APPROVED** [review]
LGTM!
