### PR TITLE
Fix custom backend provider logging on Linux

### LINKED ISSUE #1796: Fix support for ETW tracing on linux and custom backends
### Description

There's a bug in the linux trace collection which means ETW event sources inside custom backends are not collected.

The problem is in EventSourceListener.cs. Specifically, OnEventSourceCreated is called before the constructor EventSourceListener is called, thus the field durabilityProviderEventSourceName has not been initialized yet. So the comparison always fails.

### PR DESCRIPTION
**Pull request by ConnorMcMahon**
If a custom durability provider uses its ETW event source before we
instantiate the Linux logging architecture (like Netherite's ETW event
for instantiating its orchestration service), then the
OnEventSourceCreated method will call before our constructor finishes
instantiating the event source name for the custom provider. This
happens due to the ordering of constructor calls in .NET.

To work around this, we temporarily store all event sources before our
constructor establishes the durability provider event source name so
that we can enable the correct provider when we do establish the provider name.

resolves #1796

### Pull request checklist

* [x] My changes **do not** require documentation changes
    * [ ] Otherwise: Documentation PR is ready to merge and referenced in `pending_docs.md`
* [ ] My changes **should not** be added to the release notes for the next release
    * [x] Otherwise: I've added my notes to `release_notes.md`
* [x] My changes **do not** need to be backported to a previous version
    * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [x] I have added all required tests (Unit tests, E2E tests)

### CODE REVIEW

File: src/WebJobs.Extensions.DurableTask/EventSourceListener.cs [hunk 1]
```diff
@@ -32,6 +36,16 @@ public EventSourceListener(LinuxAppServiceLogger logger, bool enableVerbose, End
             this.disableVerbose = !enableVerbose; // We track the opposite value ro simplify logic later
             this.traceHelper = traceHelper;
             this.durabilityProviderEventSourceName = durabilityProviderEventSourceName;
+
+            // Check to see if any event sources were created before we knew the event source
+            //// name for the durability provider and enable that provider.
```
Comment (ConnorMcMahon) [inline src/WebJobs.Extensions.DurableTask/EventSourceListener.cs:41]: woops, extra comment `//` here.

File: test/Common/DurableTaskEndToEndTests.cs [hunk 2]
```diff
@@ -299,6 +300,55 @@ public async Task AzureStorageEmittingLogsWithEventSourceName()
...
+                    var client = await host.StartOrchestratorAsync(orchestratorName, input: "World", this.output);
+                    var status = await client.WaitForCompletionAsync(this.output);
+                    await host.StopAsync();
+                }
+
+                string consoleOutput = sw.ToString();
+
+                // Validate that the JSON has DurableTask-AzureStorage fields
+                string[] lines = consoleOutput.Split('\n');
+                var azureStorageLogLines = lines.Where(l => l.Contains("DurableTask-CustomSource") && l.StartsWith(prefix));
```
Comment (ConnorMcMahon) [inline test/Common/DurableTaskEndToEndTests.cs:347]: should change name of variable here.

**Review by davidmrdavid — COMMENTED** [review]
Thank you for this change! Seems like there are a few minor typos to address and I also left some comments.

Also, a question: Wouldn't it be possible to read the value for the durability provider from the app configuration itself inside of `OnEventSourceCreated`? 
Say, would it be possible to read it as an environment variable when `this.durabilityProviderEventSourceName` is `null`?

I think that would be a cleaner approach.

**Review by davidmrdavid — APPROVED** [review]
LGTM so long as CI goes 🟢

**Review by bachuv — APPROVED** [review]
