### PR TITLE
DurableHttpRequest Content exception during location polling

### LINKED ISSUE #1344: DurableHttpRequest Throws Exception When Content Is Supplied
### Description
After instantiating a DurableHttpRequest with content and calling CallHttpAsync an exception is thrown specifying a BadRequest was made.

### Expected behavior
The Content (JSON in this case) supplied to the initial DurableHttpRequest should not be passed to the new DurableHttpRequest created in the CreateLocationPollRequest method.

### Actual behavior
The Content from the original request is copied into this request that polls the Location URI returned 
in the header of the initial request. This causes an exception to the thrown and the Azure Function to terminate.

### Relevant source code snippets
```csharp
private DurableHttpRequest CreateLocationPollRequest(DurableHttpRequest durableHttpRequest, string locationUri)
{
	DurableHttpRequest newDurableHttpRequest = new DurableHttpRequest(
		method: HttpMethod.Get,
		uri: new Uri(locationUri),
		headers: durableHttpRequest.Headers,
		content: durableHttpRequest.Content, // This is the line causing the issue
		tokenSource: durableHttpRequest.TokenSource);

	// Do not copy over the x-functions-key header, as in many cases, the
	// functions key used for the initial request will be a Function-level key
	// and the status endpoint requires a master key.
	newDurableHttpRequest.Headers.Remove("x-functions-key");

	return newDurableHttpRequest;
}
```

### Known workarounds
After cloning this repo and referencing it in my project instead of the NuGet package I commented out the line using the initial Content and published my Azure function. It no longer throws an exception and correctly waits until the task (a CopyDatabase operation in my case) is complete.

### PR DESCRIPTION
**Pull request by bachuv**
This change resolves #1344 . The location polling request is a GET request, so removing the content should be fine.

### CODE REVIEW

File: src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableOrchestrationContext.cs [hunk 1]
```diff
@@ -292,7 +292,6 @@ private DurableHttpRequest CreateLocationPollRequest(DurableHttpRequest durableH
                 method: HttpMethod.Get,
                 uri: new Uri(locationUri),
                 headers: durableHttpRequest.Headers,
```
Comment (cgillum) [inline src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableOrchestrationContext.cs:294]: Maybe this can be a separate PR, but I wonder if we need to reduce the set of headers we send to the polling endpoint. I recall there were some issues with this that Connor had to fix at one point.

Comment (ConnorMcMahon) [reply src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableOrchestrationContext.cs:294]: Yeah. I think the assumption we made when designing this feature was that the request would be identical to the initial request, just with a different URI.

I think it has been made clear that in practice this can lead to some problems. I'm not sure what the proper default polling request looks like honestly. I'm a bit afraid to make to many drastic changes do to it technically being a breaking change, but I think we can spin this as more of a bug fix. Once we tackle #1183, we will have given everyone a wide enough escape valve that if they don't like our defaults, they can use their own thankfully.
