### PR TITLE
Fix missing dedupe states for gRPC client server impl

### LINKED ISSUE #2466: Singleton out of process orchestrator two running at the same time
Hi,
We've used the singleton pattern for our orchestrator to make sure only one execution is performed at one time, because of a critical section regarding two sequential operations, see  https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-singletons?tabs=csharp#singleton-example

Now when we've tested it, sometimes the orchestration will have to instances running at the same time. We can see logs from one activity in the orchestrator is running at the same time and failing because of it.

Is this pattern broken in the out of process worker?

### PR DESCRIPTION
**Pull request by jviau**
Fixes missing dedupe states in the gRPC server client when scheduling a new orchestration via `IOrchestrationServiceClient`. Without the dedupe states, we would effectively restart already running orchestrations when it was scheduled again.

### Issue describing the changes in this PR

resolves #2466

### Pull request checklist

* [x] My changes **do not** require documentation changes
    * [ ] Otherwise: Documentation PR is ready to merge and referenced in `pending_docs.md`
* [ ] My changes **should not** be added to the release notes for the next release
    * [ ] Otherwise: I've added my notes to `release_notes.md` -- TODO
* [x] My changes **do not** need to be backported to a previous version
    * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [ ] I have added all required tests (Unit tests, E2E tests)
* [x] My changes **do not** require any extra work to be leveraged by OutOfProc SDKs
    * [ ] Otherwise: That work is being tracked here: #issue_or_pr_in_each_sdk
* [x] My changes **do not** change the version of the WebJobs.Extensions.DurableTask package
    * [ ] Otherwise: major or minor version updates are reflected in `/src/Worker.Extensions.DurableTask/AssemblyInfo.cs`
* [x] My changes **do not** add EventIds to our EventSource logs
    * [ ] Otherwise: Ensure the EventIds are within the supported range in our existing Windows infrastructure. You may validate this with a deployed app's telemetry. You may also extend the range by completing a PR such as [this one](https://msazure.visualstudio.com/One/_git/AAPT-Antares-Websites/pullrequest/7463263?_a=files).

### CODE REVIEW

File: src/WebJobs.Extensions.DurableTask/OverridableStates.cs [hunk 1]
```diff
@@ -21,4 +24,33 @@ public enum OverridableStates
...
+#pragma warning disable SA1649 // File name should match first type name Justification: pairing extension methods with enum.
+    internal static class OverridableStatesExtensions
+#pragma warning restore SA1649 // File name should match first type name
+    {
+        private static readonly OrchestrationStatus[] NonRunning = new OrchestrationStatus[]
+        {
+            OrchestrationStatus.Running,
+            OrchestrationStatus.ContinuedAsNew,
+            OrchestrationStatus.Pending,
+        };
```
Comment (cgillum) [inline src/WebJobs.Extensions.DurableTask/OverridableStates.cs:40]: Does `Suspended` need to be in this list?

File: src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableClient.cs [hunk 2]
```diff
@@ -213,18 +213,8 @@ async Task<string> IDurableOrchestrationClient.StartNewAsync<T>(string orchestra
...
-                {
-                    OrchestrationStatus.Running,
-                    OrchestrationStatus.ContinuedAsNew,
-                    OrchestrationStatus.Pending,
-                };
-            }
-
-            return new OrchestrationStatus[0];
+            OverridableStates overridableStates = this.durableTaskOptions.OverridableExistingInstanceStates;
+            return overridableStates.ToDedupeStatuses();
```
Comment (cgillum) [inline src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableClient.cs:217]: I'm confused. The method name is `GetStatusesNotToOverride`, but the value we're returning seems to be the opposite of this: `overridableStates`. Why is this logic correct? Assuming it is correct, can we rename something to make it _obviously_ correct?

File: src/WebJobs.Extensions.DurableTask/OverridableStates.cs (hunk 1 above)
Comment (jviau) [reply src/WebJobs.Extensions.DurableTask/OverridableStates.cs:40]: Yeah, I think that is a good change. Might even be a bug fix for all other DF languages

**Comment by cgillum** [comment]
I think this Java issue will get resolved by this PR as well: https://github.com/microsoft/durabletask-java/issues/135

**Review by cgillum — APPROVED** [review]
