### PR TITLE
Fixing URLs containing Orchestration Instances IDs with Spaces

### LINKED ISSUE #2590: IDurableOrchestrationClient.CreateCheckStatusResponse returns bad URI when instanceId contains a space
### Description

InstanceId contains a space between two "_" characters== “ModelV2_2023-09-11_ _OFFICIAL_2023-09-12-14-51-25.384”

IDurableOrchestrationClient.CreateCheckStatusResponse(req, instanceId) returns a json with statusQueryUri == “https://<redacted>.azurewebsites.net/runtime/webhooks/durabletask/instances/ModelV2_2023-09-11_+_OFFICIAL_2023-09-12-14-51-25.384?taskHub=CMASModelSimulatorTest&connection=Storage&code=IjLtwaeAWWKYHbGIeoY7-rAC0dC5FwCL1BtEQJQlA0OQAzFuO5ZwSg==”

### Expected behavior
StatusQueryUri can be used to fetch the status.

### Actual behavior
StatusQueryUri is invalid, http call returns 404. If I replace the "+" with a space in Postman, it works.

### Relevant source code snippets
            await orchestrationClient.StartNewAsync(nameof(Orchestrator.RunOrchestrator), instanceId, orchestratorInput);
            return orchestrationClient.CreateCheckStatusResponse(req, instanceId); // return to http caller

### Known workarounds
Avoid space in instancedId

### App Details

- Durable Functions extension version: 2.9.2
- Azure Functions runtime version (1.0 or 2.0): 4.25.2.21138
- Programming language used: C#

- **Timeframe issue observed**:
- **Function App name**:
- **Function name(s)**:
- **Azure region**:
- **Orchestration instance ID(s)**:
- **Azure storage account name**:

> If you don't want to share your Function App or storage account name GitHub, please at least share the orchestration instance ID. Otherwise it's extremely difficult to look up information.

### PR DESCRIPTION
**Pull request by sophiatev**
### Fixing URLs containing Orchestration Instances IDs with Spaces

Resolves #2590 where the URLs containing the orchestration instance ID were returning a 404 when the instance ID had spaces. Also added a simple test to make sure that the URL is correctly parsed in this case, specifically testing the "statusQueryGetUri". 

### Pull request checklist

* [x] My changes **do not** require documentation changes
    * [ ] Otherwise: Documentation PR is ready to merge and referenced in `pending_docs.md`
* [x] My changes **should not** be added to the release notes for the next release
    * [ ] Otherwise: I've added my notes to `release_notes.md`
* [x] My changes **do not** need to be backported to a previous version
    * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [x] I have added all required tests (Unit tests, E2E tests)
* [x] My changes **do not** require any extra work to be leveraged by OutOfProc SDKs
    * [ ] Otherwise: That work is being tracked here: #issue_or_pr_in_each_sdk
* [x] My changes **do not** change the version of the WebJobs.Extensions.DurableTask package
    * [ ] Otherwise: major or minor version updates are reflected in `/src/Worker.Extensions.DurableTask/AssemblyInfo.cs`
* [x] My changes **do not** add EventIds to our EventSource logs
    * [ ] Otherwise: Ensure the EventIds are within the supported range in our existing Windows infrastructure. You may validate this with a deployed app's telemetry. You may also extend the range by completing a PR such as [this one](https://msazure.visualstudio.com/One/_git/AAPT-Antares-Websites/pullrequest/7463263?_a=files).
* [ ] My changes **should** be added to **v2.x** branch.
    * [ ] Otherwise: This change applies exclusively to WebJobs.Extensions.DurableTask v3.x. It will be retained only in the `dev` and `main` branches and will not be merged into the `v2.x` branch.

### CODE REVIEW

File: test/Common/HttpApiHandlerTests.cs [hunk 1]
```diff
@@ -807,6 +807,40 @@ public async Task GetQueryWithoutRuntimeStatus_is_Success()
...
+            getStatusRequestUriBuilder.Path += $"/Instances/" + WebUtility.UrlEncode(instanceId);
+
+            var responseMessage = await httpApiHandler.HandleRequestAsync(
+                new HttpRequestMessage
+                {
+                    Method = HttpMethod.Get,
+                    RequestUri = getStatusRequestUriBuilder.Uri,
+                });
+
+            Assert.Equal(HttpStatusCode.OK, responseMessage.StatusCode);
```
Comment (nytian) [inline test/Common/HttpApiHandlerTests.cs:842]: Can we also add a assert here to make sure the instanceId returned is correct?

**Review by nytian — APPROVED** [review]
Thanks for the PR, and adding the test!

File: test/Common/HttpApiHandlerTests.cs (hunk 1 above)
Comment (sophiatev) [reply test/Common/HttpApiHandlerTests.cs:842]: Done :)

File: test/Common/HttpApiHandlerTests.cs [hunk 2]
```diff
@@ -807,6 +807,42 @@ public async Task GetQueryWithoutRuntimeStatus_is_Success()
             Assert.Equal("Completed", actual[1].RuntimeStatus);
         }
 
+        [Fact]
+        [Trait("Category", PlatformSpecificHelpers.TestCategory)]
+        public async Task HandleGetStatusRequestAsync_Correctly_Parses_InstanceId_With_Spaces()
+        {
+            var instanceId = "test instance id with spaces";
+            var list = (IList<DurableOrchestrationStatus>)new List<DurableOrchestrationStatus>
```
Comment (bachuv) [inline test/Common/HttpApiHandlerTests.cs]: Can we update this line and remove `(IList<DurableOrchestrationStatus>)`?
```suggestion
            var list = new List<DurableOrchestrationStatus>

```

**Review by bachuv — COMMENTED** [review]
Thanks for contributing this fix!
