### PR TITLE
Fix Local RPC race condition on app startup

### LINKED ISSUE #1273: Local HTTP listener causing startup issues
Tracking this information as an issue here from @olitomlinson. Quotes below from him:

I've got an open support case (120031225000535) because my DF app failed to start up for approx 30 minutes and then eventually corrected itself without intervention.

The error message during startup was :

`Failed to bind to address http://127.0.0.1:17071: address already in use.
Only one usage of each socket address (protocol/network address/port) is normally permitted`

My non-scientific googling has brought me to this GitHub issue. I don't really know if this work item impacts my particular issue, it probably doesn't, but are you in a position to shed any light? No worries if not, ill just keep following up with support to get to the root cause. Thanks in advance!

### PR DESCRIPTION
**Pull request by ConnorMcMahon**
Our previous attempt to dynamically select ports for the local RPC endpoint fixed many issues customers had, but there still exists a race condition when multiple hosts start up at the same time. To completely resolve this issue, this PR makes the following changes:

- Move the code that finds a free port closer to the code that attempts to listen on that port.
- Add a retry layer if the free port has been taken by another worker between when we found the free port and when we tried to listen to that port.
- If we somehow hit this race condition 3 times in a row, even though it should be more rare now, we gracefully fallback to using the public endpoints for out-of-process clients instead of failing to start up the host.

resolves #1273

### Pull request checklist

* [x] My changes **do not** require documentation changes
    * [ ] Otherwise: Documentation PR is ready to merge and referenced in `pending_docs.md`
* [ ] My changes **should not** be added to the release notes for the next release
    * [X] Otherwise: I've added my notes to `release_notes.md`
* [ ] My changes **do not** need to be backported to a previous version
    * [X] Otherwise: Backport tracked by issue/PR #1723
* [X] I have added all required tests (Unit tests, E2E tests)

### CODE REVIEW

File: src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs [hunk 1]
```diff
@@ -1140,13 +1140,15 @@ private void ThrowIfWebhooksNotConfigured()
 
         internal bool TryGetRpcBaseUrl(out Uri rpcBaseUrl)
         {
-            if (this.durableTaskOptions.LocalRpcEndpointEnabled != false)
+            if (this.durableTaskOptions.LocalRpcEndpointEnabled != false
+                && this.localHttpListener.IsListening)
```
Comment (davidmrdavid) [inline src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs:1144]: nit: I would prefer if we didn't introduce the double negative with "!= false"
```suggestion
            if (this.durableTaskOptions.LocalRpcEndpointEnabled
                && this.localHttpListener.IsListening)

```

File: src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs [hunk 2]
```diff
@@ -1140,13 +1140,15 @@ private void ThrowIfWebhooksNotConfigured()
...
+            if (this.durableTaskOptions.LocalRpcEndpointEnabled != false
+                && this.localHttpListener.IsListening)
             {
                 rpcBaseUrl = this.localHttpListener.InternalRpcUri;
                 return true;
             }
 
-            // The app owner explicitly disabled the local RPC endpoint.
+            // The app owner explicitly disabled the local RPC endpoint, or we were unable to
+            // successfully find a port after several tries.
```
Comment (davidmrdavid) [inline src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs:1151]: I don't see the "several tries" logic in here. If it's elsewhere, could we document that?

File: src/WebJobs.Extensions.DurableTask/LocalHttpListener.cs [hunk 3]
```diff
@@ -66,8 +55,35 @@ public async Task StartAsync()
...
+                        .UseKestrel()
+                        .UseUrls(listenUri.OriginalString)
+                        .Configure(a => a.Run(this.HandleRequestAsync))
+                        .Build();
+
+                    await this.localWebHost.StartAsync();
+                    this.IsListening = true;
+                    break;
+                }
+                catch
```
Comment (davidmrdavid) [inline src/WebJobs.Extensions.DurableTask/LocalHttpListener.cs:76]: Should we try to catch a more specific exception?

File: test/Common/DurableTaskEndToEndTests.cs [hunk 4]
```diff
@@ -4796,35 +4796,43 @@ public async Task CallActivity_Like_From_Azure_Portal()
...
-            {
-                await host2.StartAsync();
-            }
-            catch (Exception)
-            {
-                Assert.True(false, "Could not start up two hosts on the same device in parallel");
-            }
-            finally
+            // This test wants to be sure there are no race conditions while starting up multiple hosts in parallel,
+            // so attempt various times to make sure to hit race condition if it exists.
```
Comment (davidmrdavid) [inline test/Common/DurableTaskEndToEndTests.cs:4806]: nit: replace "make sure" with "try" or "attempt"
```suggestion
            // so attempt various times to try to hit race condition if it exists.

```

**Review by davidmrdavid — APPROVED** [review]
Looks good to me, left some stylistic requests and some questions. Some comments were not associated with the review itself but please give those a look as well. Thanks!

File: src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs (hunk 1 above)
Comment (cgillum) [reply src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs:1144]: Unfortunately the two expressions are not equivalent because `LocalRpcEndpointEnabled` is not a bool, but a bool? (i.e. `Nullable<Boolean>`). In our case, `true`, `false`, and `null` all have different semantic meanings.

Comment (davidmrdavid) [reply src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs:1144]: Ah, that makes sense. Thanks for clarifying!

File: src/WebJobs.Extensions.DurableTask/LocalHttpListener.cs [hunk 5]
```diff
@@ -36,27 +36,16 @@ internal class LocalHttpListener : IDisposable
...
-#endif
         }
 
-        public Uri InternalRpcUri { get; }
+        public Uri InternalRpcUri { get; private set; }
 
         public bool IsListening { get; private set; }
 
-        public void Dispose() => this.localWebHost.Dispose();
+        public void Dispose() => this.localWebHost?.Dispose();
```
Comment (cgillum) [inline src/WebJobs.Extensions.DurableTask/LocalHttpListener.cs:48]: It doesn't look like `this.localWebHost` can ever be since we assign it in the constructor. We also never explicitly assign it to null. Is this a leftover artifact of an earlier iteration?

File: src/WebJobs.Extensions.DurableTask/LocalHttpListener.cs [hunk 6]
```diff
@@ -36,27 +36,16 @@ internal class LocalHttpListener : IDisposable
...
-                .UseKestrel()
-                .UseUrls(listenUri.OriginalString)
-                .Configure(a => a.Run(this.HandleRequestAsync))
-                .Build();
-#else
-            // Just use default port for internal Uri. No need to check for port availability since
-            // we won't be listening to this endpoint.
-            this.InternalRpcUri = new Uri($"http://127.0.0.1:{DefaultPort}/durabletask/");
+            // Set to a non null value
+            this.InternalRpcUri = new Uri($"http://127.0.0.1:{DefaultPort}/defaultvalue/");
```
Comment (cgillum) [inline src/WebJobs.Extensions.DurableTask/LocalHttpListener.cs:40]: What's the reasoning behind changing "/durabletask/" to "/defaultvalue/" here?

If this is intended to be a dummy value, I would suggest we make that more explicit - e.g. http://uninitialized.

File: test/Common/DurableTaskEndToEndTests.cs [hunk 7]
```diff
@@ -4796,35 +4796,43 @@ public async Task CallActivity_Like_From_Azure_Portal()
...
+            int numAttempts = 5;
+            for (int attempt = 0; attempt < numAttempts; attempt++)
             {
-                await host1.StopAsync();
-                host1.Dispose();
-                await host2.StopAsync();
-                host2.Dispose();
+                int numHost = 10;
```
Comment (cgillum) [inline test/Common/DurableTaskEndToEndTests.cs:4810]: naming nit: consider `threadCount` as the name of this local variable. It's a better match for it's intended use.

File: src/WebJobs.Extensions.DurableTask/LocalHttpListener.cs [hunk 8]
```diff
@@ -66,8 +55,35 @@ public async Task StartAsync()
...
+                {
+                    this.traceHelper.ExtensionWarningEvent(
+                        this.durableTaskOptions.HubName,
+                        functionName: string.Empty,
+                        instanceId: string.Empty,
+                        message: $"Failed to open local socket {availablePort}. This was attempt #{numAttempts} to open a local port.");
+                    numAttempts++;
+                }
+            }
+            while (numAttempts <= 3);
```
Comment (cgillum) [inline src/WebJobs.Extensions.DurableTask/LocalHttpListener.cs:86]: I wonder if we should try more times, like 10. I also wonder if we should have a small sleep in-between retries. I'm not sure how random the port selection is, so it would be nice if we could mitigate the case where two hosts are starting up at the same time and selecting the same random sequence of available port numbers.

**Review by cgillum — COMMENTED** [review]
Mostly nits. My only real concern is what to do if we fail to find a free port. I'm not super comfortable to falling back to public endpoints because that could put a customer into an unpredictable state - i.e. it works on some machines but not on others - and diagnosing such issues will be a lot harder. I'm also not sure what this means when someone is running outside of the Azure Functions hosted service (K8s, WebJobs, etc.) where they may not have any public HTTP endpoints. Throwing an exception might actually be safer.

File: src/WebJobs.Extensions.DurableTask/LocalHttpListener.cs (hunk 5 above)
Comment (ConnorMcMahon) [reply src/WebJobs.Extensions.DurableTask/LocalHttpListener.cs:48]: Indeed. Good catch.

File: src/WebJobs.Extensions.DurableTask/LocalHttpListener.cs (hunk 8 above)
Comment (ConnorMcMahon) [reply src/WebJobs.Extensions.DurableTask/LocalHttpListener.cs:86]: Makes sense. if we are worried about them being in sync, would doing a semi-random amount of sleep time help (i.e. between 50-100 ms)? That way we keep the two hosts out of lockstep.

**Comment by ConnorMcMahon** [comment]
@cgillum, I am a bit afraid about just throwing an exception, because I don't know if that shuts down the whole host. I know some customers who hit the current race condition seem to hit to be stuck in a bad state. Would a failfast be better?

**Comment by cgillum** [comment]
Oy...if an exception here doesn't restart the host then that would be really bad. I hate to resort to FailFast because that's a pretty severe hammer, but I guess I don't have any better ideas than this...

**Comment by ConnorMcMahon** [comment]
I'll see if I can find an example of what happens when an exception is thrown. Overall, I expect this to happen incredibly rarely, especially if we up the retry count to 10 and add some randomized delays, as we have already made the race condition less likely by reducing the time window between port selection and listening on that port.

File: src/WebJobs.Extensions.DurableTask/LocalHttpListener.cs (hunk 8 above)
Comment (ConnorMcMahon) [reply src/WebJobs.Extensions.DurableTask/LocalHttpListener.cs]: Added a dynamic sleep between 0 and 1 seconds here. Let me know if that's what you had in mind.

File: src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs (hunk 2 above)
Comment (ConnorMcMahon) [reply src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs]: I just removed that, because now this code shouldn't fail if we failed to start up, since we are throwing an exception.

**Review by cgillum — APPROVED** [review]
LGTM!
