### PR TITLE
Fix: Apply default version to entity-scheduled orchestrations

### LINKED ISSUE #3237: Scheduling an orchestration from entity seem to ignore default version
### Description
As part of an orchestration migration, we decided to check out orchestraiton versioning framework.
We introduced version guards to allow both old and new workflows, and configured `host.json` to now issue a default version.

### Expected behavior
All orchestrations started by executors after the code delpoyment should have new default version assigned (and execute new code path.

### Actual behavior
The orchestration scheduled from entity seems to have no version (and it is the one where we introduced version-based migration). All child orcehstrations, however, have version assigned as expected.

Part of `host.json`

```
"durableTask": {
      "hubName": "TaskHub",
      "tracing": {
        "DistributedTracingEnabled": true,
        "Version": "V2"
      },
      "defaultVersion": "2025-10-23"
    }
```

Part of logic
```csharp
    // Scheduled from entity
    [Function(nameof(ExecuteWorkload))]
    public async Task Run([OrchestrationTrigger] TaskOrchestrationContext context, ExecutionContext input)
    {
        var logger = context.CreateReplaySafeLogger<ExecuteWorkload>();
        var (tenantId, sessionId, executionScenario, version) = input;

       // This should execute on fresh runners only, however, it is skipped
        if (context.IsVersionEqualOrNewerThan(VersionManagement.V20251023))
        {
            version = await GetCurrentSnapshotVersion.CallActivity(context, tenantId);
        }

        var isSuccessful = true;
        try
        {
            // This orchestration has version assigned to it
            sessionId ??= await SpinUpSession.CallOrchestration(context, tenantId);
           // etc

```

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: `Microsoft.Azure.Functions.Worker.Extensions.DurableTask v1.8.0`
- **Azure Functions runtime version (1.0 or 2.0)**: 2.0
- **Programming language used**: C#

### Screenshots

Image

### PR DESCRIPTION
**Pull request by torosent**
### Description
This PR fixes an issue where orchestrations scheduled by entities in the isolated worker model were not receiving the host's `defaultVersion` configuration when no explicit version was provided.

### Issue describing the changes in this PR

resolves #3237

### Problem
When entities in the isolated worker model call `Context.ScheduleNewOrchestration()` without specifying a version, the orchestration was receiving a null/empty version instead of the `defaultVersion` configured in `host.json` (e.g., "2.0"). This caused version mismatch errors.

### Solution
1.  Modified `ProtobufUtils.ToOperationAction` and `ToEntityBatchResult` to accept an optional `defaultVersion` parameter.
2.  Updated `ToOperationAction` to apply `defaultVersion` when the protobuf message's version is null or empty.
3.  Updated `OutOfProcMiddleware` to pass `this.Options.DefaultVersion` when converting entity batch results.

### Verification
- **Unit Tests:** Added 21 new tests in `ProtobufUtilsTests.cs` covering version resolution logic, batch processing, and backward compatibility.
- **Integration Tests:** Added new E2E tests (`EntityVersioningTests.cs`) and a test entity (`VersionSchedulerEntity`) to verify that orchestrations scheduled by entities correctly receive the host's default version.

### Pull request checklist

* [x] My changes **do not** require documentation changes
    * [ ] Otherwise: Documentation PR is ready to merge and referenced in `pending_docs.md`
* [ ] My changes **should not** be added to the release notes for the next release
    * [ ] Otherwise: I've added my notes to `release_notes.md`
* [x] My changes **do not** need to be backported to a previous version
    * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [x] I have added all required tests (Unit tests, E2E tests)
* [x] My changes **do not** require any extra work to be leveraged by OutOfProc SDKs
    * [ ] Otherwise: That work is being tracked here: #issue_or_pr_in_each_sdk
* [x] My changes **do not** change the version of the WebJobs.Extensions.DurableTask package
    * [ ] Otherwise: major or minor version updates are reflected in `/src/Worker.Extensions.DurableTask/AssemblyInfo.cs`
* [x] My changes **do not** add EventIds to our EventSource logs
    * [ ] Otherwise: Ensure the EventIds are within the supported range in our existing Windows infrastructure. You may validate this with a deployed app's telemetry. You may also extend the range by completing a PR such as [this one](https://msazure.visualstudio.com/One/_git/AAPT-Antares-Websites/pullrequest/7463263?_a=files).
* [ ] My changes **should** be added to **v2.x** branch.
    * [ ] Otherwise: This change applies exclusively to WebJobs.Extensions.DurableTask v3.x. It will be retained only in the `dev` and `main` branches and will not be merged into the `v2.x` branch.

### CODE REVIEW

File: test/e2e/Tests/Tests/EntityVersioningTests.cs [hunk 1]
```diff
@@ -0,0 +1,119 @@
...
+// Licensed under the MIT License. See License.txt in the project root for license information.
+
+using System.Net;
+using Xunit;
+using Xunit.Abstractions;
+
+namespace Microsoft.Azure.Durable.Tests.DotnetIsolatedE2E;
+
+/// <summary>
+/// These tests verify that when an entity schedules an orchestration without specifying a version,
```
Comment (AnatoliB) [inline test/e2e/Tests/Tests/EntityVersioningTests.cs]: This comment is already outdated: the tests below verify more than that. Consider removing this entire comment, the individual test comments are probably enough.

File: test/e2e/Tests/Tests/EntityVersioningTests.cs [hunk 2]
```diff
@@ -0,0 +1,119 @@
...
+    {
+        _fixture = fixture;
+        _fixture.TestLogs.UseTestLogger(testOutputHelper);
+        _output = testOutputHelper;
+    }
+
+    /// <summary>
+    /// Tests that when an entity schedules an orchestration without specifying a version,
+    /// the orchestration receives the host's defaultVersion from host.json.
+    /// This is the main fix for GitHub issue #3237.
```
Comment (AnatoliB) [inline test/e2e/Tests/Tests/EntityVersioningTests.cs]: Nit: the GitHub issue reference looks unnecessary: GitHub is already doing a great job associating code changes with PRs and issues, and this line will become confusing if this code is copied or migrated.

File: test/e2e/Tests/Tests/EntityVersioningTests.cs [hunk 3]
```diff
@@ -0,0 +1,119 @@
...
+        // Assert: Verify the request was accepted
+        Assert.Equal(HttpStatusCode.Accepted, response.StatusCode);
+
+        string statusQueryGetUri = await DurableHelpers.ParseStatusQueryGetUriAsync(response);
+        await DurableHelpers.WaitForOrchestrationStateAsync(statusQueryGetUri, "Completed", 60);
+
+        var orchestrationDetails = await DurableHelpers.GetRunningOrchestrationDetailsAsync(statusQueryGetUri);
+
+        // The scheduled orchestration should have received the default version "2.0" from host.json
+        // This verifies the fix for GitHub issue #3237
```
Comment (AnatoliB) [inline test/e2e/Tests/Tests/EntityVersioningTests.cs]: Unnecessary GitHub issue reference

File: test/FunctionsV2/ProtobufUtilsTests.cs [hunk 4]
```diff
@@ -0,0 +1,389 @@
...
+
+            // Assert
+            Assert.NotNull(result);
+            var sendSignalResult = Assert.IsType<SendSignalOperationAction>(result);
+            Assert.Equal("TestOperation", sendSignalResult.Name);
+            Assert.Equal("@entity@test", sendSignalResult.InstanceId);
+        }
+
+        /// <summary>
+        /// Tests backward compatibility - when no default version is provided, behavior should match previous implementation.
```
Comment (AnatoliB) [inline test/FunctionsV2/ProtobufUtilsTests.cs]: Nit: the notion of "backward compatibility" and "previous implementation" will become outdated soon after this PR is merged. Consider removing it from the comment and the test name.

File: test/FunctionsV2/ProtobufUtilsTests.cs [hunk 5]
```diff
@@ -0,0 +1,389 @@
...
+
+            // Assert
+            Assert.NotNull(result);
+            Assert.Single(result.Actions);
+            var action = Assert.IsType<StartNewOrchestrationOperationAction>(result.Actions[0]);
+            Assert.Equal(defaultVersion, action.Version);
+        }
+
+        /// <summary>
+        /// Tests that SendSignalOperationAction is not affected by the default version parameter.
```
Comment (AnatoliB) [inline test/FunctionsV2/ProtobufUtilsTests.cs]: Is there anything special specifically about SendSignalOperationAction, or it's just used as an example of an action where the version is irrelevant? If this is just an example, let's say it. However, let's even consider removing this test: strictly speaking, it does not really verify what it claims.

Comment (torosent) [reply test/FunctionsV2/ProtobufUtilsTests.cs]: Fixed

File: test/FunctionsV2/ProtobufUtilsTests.cs (hunk 4 above)
Comment (torosent) [reply test/FunctionsV2/ProtobufUtilsTests.cs]: Fixed

File: test/e2e/Tests/Tests/EntityVersioningTests.cs (hunk 3 above)
Comment (torosent) [reply test/e2e/Tests/Tests/EntityVersioningTests.cs]: Fixed

File: test/e2e/Tests/Tests/EntityVersioningTests.cs (hunk 2 above)
Comment (torosent) [reply test/e2e/Tests/Tests/EntityVersioningTests.cs]: Fixed

File: test/e2e/Tests/Tests/EntityVersioningTests.cs (hunk 1 above)
Comment (torosent) [reply test/e2e/Tests/Tests/EntityVersioningTests.cs]: Fixed

**Review by AnatoliB — APPROVED** [review]
