### PR TITLE
Fix byte[] Input Handling in Activity Functions at .NET Isolated 

### LINKED ISSUE #2746: ActivityTrigger with byte[] as input results in null reference exception after upgrade to Microsoft.Azure.Functions.Worker.Extensions.DurableTask 1.1.1
### Description
After upgrading from `Microsoft.Azure.Functions.Worker.Extensions.DurableTask` **1.0.4** to **1.1.1** my ActivityTrigger functions throw an exception on a `byte[]` binding parameter.

I have an Azure Durable Function and my orchestrator invokes an `ActivityTrigger` Function which returns a `byte[][]`. I then use a fan-out/fan-in pattern to process each `byte[]` in this array in parallel. With package version 1.0.4 this works, but after upgrading to 1.1.1 calling the ActivityTrigger throws an exception.

I reported this before in https://github.com/Azure/azure-functions-durable-extension/issues/2678 which was closed as duplicate and I hoped it would be resolved with version 1.1.1, but unfortunately the issue still occurs in the latest version.

### Expected behavior
The Function with ActivityTrigger should accept `byte[]` as valid input.

### Actual behavior
The following exception is thrown in the autogenerated `DirectFunctionExecutor`

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=FunctionApp
  StackTrace:
   at FunctionApp.DirectFunctionExecutor.<ExecuteAsync>d__3.MoveNext() in C:\Users\[redacted]\source\repos\Sandbox\FunctionApp\Microsoft.Azure.Functions.Worker.Sdk.Generators\Microsoft.Azure.Functions.Worker.Sdk.Generators.FunctionExecutorGenerator\GeneratedFunctionExecutor.g.cs:line 50

  This exception was originally thrown at this call stack:
    FunctionApp.DirectFunctionExecutor.ExecuteAsync(Microsoft.Azure.Functions.Worker.FunctionContext) in GeneratedFunctionExecutor.g.cs
```

### Relevant source code snippets

Create a new empty Function App. Change the Program.cs to the following:

```csharp
using Microsoft.Azure.Functions.Worker;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

var host = new HostBuilder()
    .ConfigureFunctionsWorkerDefaults()
    .ConfigureServices(services =>
    {
        services.AddApplicationInsightsTelemetryWorkerService();
        services.ConfigureFunctionsApplicationInsights();
    })
    .Build();

host.Run();
```

And create class `FanOutByteArrayOrchestrator.cs` with the below content:

```csharp
using Microsoft.Azure.Functions.Worker;
using Microsoft.Azure.Functions.Worker.Http;
using Microsoft.DurableTask;
using Microsoft.DurableTask.Client;
using System.Text;
using System.Text.Json;

namespace FunctionApp
{
    public class FanOutByteArrayOrchestrator
    {
        [Function("FanOutByteArrayOrchestratorApi")]
        public async Task<HttpResponseData> RunApi(
            [HttpTrigger] HttpRequestData request,
            [DurableClient] DurableTaskClient durableTaskClient)
        {
            var orchestrationInstanceId = await durableTaskClient
                .ScheduleNewOrchestrationInstanceAsync("FanOutByteArrayOrchestrator")
                .ConfigureAwait(true);

            return durableTaskClient.CreateCheckStatusResponse(request, orchestrationInstanceId);
        }

        [Function("FanOutByteArrayOrchestrator")]
        public async Task Run(
            [OrchestrationTrigger] TaskOrchestrationContext taskOrchestrationContext)
        {
            var events = await taskOrchestrationContext
                .CallActivityAsync<byte[][]>("CreateEvents")
                .ConfigureAwait(true);

            // Fan-out/fan-in
            var eventTasks = events
                .Select(x => taskOrchestrationContext.CallActivityAsync("ProcessEvent", input: x))
                .ToList();
            await Task.WhenAll(eventTasks).ConfigureAwait(true);
        }

        [Function("CreateEvents")]
        public Task<byte[][]> CreateEvents([ActivityTrigger] CancellationToken cancellationToken)
        {
            var cars = new List<Car>
            {
                new() { HorsePower = 500, Name = "Tesla Model 3"},
                new() { HorsePower = 1000, Name = "Red Bull Formula 1 Car"},
            };

            var byteArray = cars.Select(x => Encoding.UTF8.GetBytes(JsonSerializer.Serialize(x)));

            return Task.FromResult(byteArray.ToArray());
        }

        [Function("ProcessEvent")]
        public Task ProcessEvent([ActivityTrigger] byte[] eventToProcess, CancellationToken cancellationToken)
        {
            var jsonString = Encoding.UTF8.GetString(eventToProcess);
            var car = JsonSerializer.Deserialize<Car>(jsonString);

            Console.WriteLine($"Name: {car?.Name} has {car?.HorsePower} horse power.");

            return Task.CompletedTask;
        }
    }

    internal class Car
    {
        public int HorsePower { get; set; }
        public string? Name { get; set; }
    }
}
```

Content of the .csproj file:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.21.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.DurableTask" Version="1.1.1" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.1.0" />
    <!--<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" Version="1.2.1" />-->
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.17.0" />
    <PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.22.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="1.2.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Using Include="System.Threading.ExecutionContext" Alias="ExecutionContext" />
  </ItemGroup>
</Project>
```

### Screenshot
image

### Known workarounds
Downgrade to Microsoft.Azure.Functions.Worker.Extensions.DurableTask 1.0.4.

### If deployed to Azure
Same behavior is seen when deployed to Azure - in my case an isolated azure function app.

### PR DESCRIPTION
**Pull request by nytian**
### Issue describing the changes in this PR

- resolves #2746 by adding a special case when activity inputs are byte[]
- Add e2e test that cover different type inputs of activity functions. 

### Pull request checklist

* [ ] My changes **do not** require documentation changes
    * [ ] Otherwise: Documentation PR is ready to merge and referenced in `pending_docs.md`
* [ ] My changes **should not** be added to the release notes for the next release
    * [ ] Otherwise: I've added my notes to `release_notes.md`
* [ ] My changes **do not** need to be backported to a previous version
    * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [ ] I have added all required tests (Unit tests, E2E tests)
* [ ] My changes **do not** require any extra work to be leveraged by OutOfProc SDKs
    * [ ] Otherwise: That work is being tracked here: #issue_or_pr_in_each_sdk
* [ ] My changes **do not** change the version of the WebJobs.Extensions.DurableTask package
    * [ ] Otherwise: major or minor version updates are reflected in `/src/Worker.Extensions.DurableTask/AssemblyInfo.cs`
* [ ] My changes **do not** add EventIds to our EventSource logs
    * [ ] Otherwise: Ensure the EventIds are within the supported range in our existing Windows infrastructure. You may validate this with a deployed app's telemetry. You may also extend the range by completing a PR such as [this one](https://msazure.visualstudio.com/One/_git/AAPT-Antares-Websites/pullrequest/7463263?_a=files).
* [ ] My changes **should** be added to **v2.x** branch.
    * [ ] Otherwise: This change applies exclusively to WebJobs.Extensions.DurableTask v3.x. It will be retained only in the `dev` and `main` branches and will not be merged into the `v2.x` branch.

### CODE REVIEW

**Comment by nytian** [comment]
I am not sure if this is the best way to fix this tbh. Usually for oop process( .net isoalted and java), activity functions input target type is string, -- the detonation type should always be string [here](https://github.com/Azure/azure-functions-durable-extension/blob/dev/src/WebJobs.Extensions.DurableTask/Bindings/ActivityTriggerAttributeBindingProvider.cs#L125). And that's also what we expect at [Activity Input Converter ](https://github.com/Azure/azure-functions-durable-extension/blob/dev/src/Worker.Extensions.DurableTask/ActivityInputConverter.cs#L40)at worker extension. 

But somehow when input type is byte[], the destination type is byte[] instead of string, which caused the issue here. As we will always return string from[ DurableActivityContext](https://github.com/Azure/azure-functions-durable-extension/blob/dev/src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableActivityContext.cs#L132), which will cause an error [here ](https://github.com/Azure/azure-functions-durable-extension/blob/dev/src/WebJobs.Extensions.DurableTask/Bindings/ObjectValueProvider.cs#L17) as string doesn't match byte[]. 

So that's how I updated in this PR : return a byte[] at DurableActivityContex instead of string to match the destination type which we can't change, and add a addition case at [Activity Input Converter ](https://github.com/Azure/azure-functions-durable-extension/blob/dev/src/Worker.Extensions.DurableTask/ActivityInputConverter.cs#L40). 

But I doubt if this is more like a host/worker issue as the destination type we got is wrong.

**Review by cgillum — COMMENTED** [review]
Hey @nytian. I apologize, but I'm not understanding the description of the issue. You mentioned that ooproc always expects string, but [the code you referenced](https://github.com/Azure/azure-functions-durable-extension/blob/dev/src/WebJobs.Extensions.DurableTask/Bindings/ActivityTriggerAttributeBindingProvider.cs#L125) doesn't seem to be directly related to expectations about strings.

I wonder if maybe OOProc in Azure Functions supports both `string` and `byte[]` natively, and we just need to be able to handle both?

It seems that you're doubting your solution and I'm trying to better understand why you are doubting it. Maybe you can clarify a bit more what your concerns are?

**Comment by nytian** [comment]
My apologies, and thank you for the review! @cgillum 

My main question is: based on our design, it seems that regardless of the actual input type for activity functions, the [destination type](https://github.com/Azure/azure-functions-durable-extension/blob/dev/src/WebJobs.Extensions.DurableTask/Bindings/ActivityTriggerAttributeBindingProvider.cs#L125) at binding providers should always be `string` in the modern OOP model (OutOfProcOrchestrationProtocol.MiddlewarePassthrough ). That means, after calling GetInput(see [here ](https://github.com/Azure/azure-functions-durable-extension/blob/dev/src/WebJobs.Extensions.DurableTask/Bindings/ActivityTriggerAttributeBindingProvider.cs#L142)and [here](https://github.com/Azure/azure-functions-durable-extension/blob/dev/src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableActivityContext.cs#L130)), we typically expect to receive a string. And then we match the string content and destination type [here](https://github.com/Azure/azure-functions-durable-extension/blob/dev/src/WebJobs.Extensions.DurableTask/Bindings/ActivityTriggerAttributeBindingProvider.cs#L145). And that also where we throw the error now, string doesn't match byte[]

The issue arises specifically with byte[] inputs — unlike other types, we're not getting a string as destination type, but keep it as byte[]. And that will make the match above caused [error.](https://github.com/Azure/azure-functions-durable-extension/blob/dev/src/WebJobs.Extensions.DurableTask/Bindings/ObjectValueProvider.cs#L21) From what I understand, how this value is determined is determined by the Functions host, as [this method](https://github.com/Azure/azure-functions-durable-extension/blob/dev/src/WebJobs.Extensions.DurableTask/Bindings/ActivityTriggerAttributeBindingProvider.cs#L55) should be called by host. And I didn't find how they determine this, also I’m wondering if this might actually be something that should be addressed on the host side, rather than within our layer.

My current fix works by adding an exception specifically for byte[] input, but I’m not sure this is the most ideal or scalable solution.

File: test/e2e/Apps/BasicDotNetIsolated/ActivityInputType.cs [hunk 1]
```diff
@@ -0,0 +1,137 @@
...
+
+        var items = input.Select(item => 
+            $"{{Name: {item.Name}, Age: {item.Age}, Duration: {item.Duration}, Data: [{string.Join(", ", item.Data)}]}}");
+        return $"Received CustomClass[]: [{string.Join(", ", items)}]";
+    }
+}
+
+public class CustomClass
+{
+    public string Name { get; set; }
```
Comment (andystaples) [inline test/e2e/Apps/BasicDotNetIsolated/ActivityInputType.cs]: This warning should be fixable, either by making Name nullable or setting a default value (String.Empty?)

File: test/e2e/Apps/BasicDotNetIsolated/ActivityInputType.cs [hunk 2]
```diff
@@ -0,0 +1,137 @@
...
+    public int Age { get; set; }
+    public byte[] Data { get; set; }
```
Comment (andystaples) [inline test/e2e/Apps/BasicDotNetIsolated/ActivityInputType.cs]: Same for Data

**Review by andystaples — COMMENTED** [review]
With or without the fix for byte[], this is a good e2e test to add for isolated. 
Am I understanding the discussion so far that we think the reason byte[] isn't being serialized to string like other types is due to some specific logic around byte[] in the host?

File: test/e2e/Apps/BasicDotNetIsolated/ActivityInputType.cs (hunk 1 above)
Comment (nytian) [reply test/e2e/Apps/BasicDotNetIsolated/ActivityInputType.cs]: Thanks for the review!  yeah that;s my main question: I don't know why byte[] is not treated at string like other types in host ,and thus I don't know if my fix is the ideal way. And I will update all of these warnings

**Review by cgillum — APPROVED** [review]
These are great tests. I don't know if there's a better way to fix this particular issue, but my hope is that it puts us in a better position than we were in before, and that future compatibility issues can be addressed as they are discovered.
