### PR TITLE
Analyzer: FunctionName can be constant in CallActivityAsync, Fixes InvalidCastException

### LINKED ISSUE #1287: Analyzer - Cater for activity constants and/or suppress DF109 warnings
We currently have a number of functions where we make reference to the activity name via a constant

eg.
```csharp
await context.CallActivityAsync(SendComputerVisionWorkToMonitor.EnqueuePerformComputerVisionRequestMessageActivityName,...
```

This currently raises a warning from the analyzer with 

`ProcessComputerVision.cs(49,29): warning DF0109: Activity function named 'SendComputerVisionWorkToMonitor.EnqueuePerformComputerVisionRequestMessageActivityName' does not exist. Did you mean`

Ability to resolve constant names when performing this check

Warning is thrown

### Relevant source code snippets
```csharp
await context.CallActivityAsync(SendComputerVisionWorkToMonitor.EnqueuePerformComputerVisionRequestMessageActivityName,

public const string EnqueuePerformComputerVisionRequestMessageActivityName = "EnqueuePerformComputerVisionRequestMessage";
```

If we can't achieve this check with constants, would there be a way to provide a way to suppress or exclude this check on a case by case basis? (some opt out attribute?)

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 2.2.0
- **Azure Functions runtime version (1.0 or 2.0)**: 3
- **Programming language used**: .Net

### LINKED ISSUE #1292: OrchestrationAnalyzer throwing InvalidCastException
### Description
The below compile time warning occurs after upgrading to version 2.2.0.

Warning	AD0001	Analyzer 'Microsoft.Azure.WebJobs.Extensions.DurableTask.Analyzers.OrchestratorAnalyzer' threw an exception of type 'System.InvalidCastException' with message 'Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.LocalFunctionStatementSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.MethodDeclarationSyntax'.'.

### Expected behavior
No warning, no exception thrown in analyzer.

### Actual behavior
A warning due to an analyzer exception.

### Relevant source code snippets
My best guess is that it's coming from the first line in the below method of OrchestrationAnalyzer.
```csharp
private void AnalyzeMethod(SyntaxNodeAnalysisContext context)
{
	var declaration = (MethodDeclarationSyntax)context.Node;
	if (!SyntaxNodeUtils.IsInsideOrchestrator(declaration)
		|| !SyntaxNodeUtils.IsInsideFunction(declaration))
	{
		return;
	}
	
	if (this.semanticModel == null)
	{
		this.semanticModel = context.SemanticModel;
	}

	this.orchestratorMethodDeclarations.Add(declaration);
}
```
### App Details
- Durable Functions extension version: 2.2.0
- Azure Functions runtime version: 2.0
- Programming language used: C#
- IDE: Visual Studio 16.5.1

### LINKED ISSUE #1310: Stackoverflow when running the MethodAnalyzer with 2.2.0
### Description

Starting from [this project](https://github.com/MaximRouiller/RedditEmotionAnalyzer), having the Durable Task framework to 2.2.0 makes it impossible to compile the project with .NET Core.

Link to Twitter thread: https://twitter.com/jaredpar/status/1247908047315333121

### Expected behavior

The project should compile.

### Actual behavior

> Process is terminated due to StackOverflowException
> File: Microsoft.CSharp.Core.targets

image
image

### Relevant source code snippets

https://github.com/MaximRouiller/RedditEmotionAnalyzer

### Known workarounds

Downgrading to 2.1.0

#### Azure Functions
Azure Functions Core Tools (2.7.2254 Commit hash: e06bd1a6012aa6a0859b5f30d3077947267d2b6)
Function Runtime Version: 2.0.13017.0

#### .NET Core

.NET Core SDK (reflecting any global.json):
 Version:   3.1.300-preview-015048
 Commit:    13f19b4682

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.300-preview-015048\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  3.1.100 [C:\Program Files\dotnet\sdk]
  3.1.300-preview-015048 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

### Screenshots

image

### PR DESCRIPTION
**Pull request by amdeel**
resolves #1292 
resolves #1287 
resolves #1310 

Fixes an issue where Orchestrator analyzer threw an InvalidCastException, casting to MethodDeclarationSyntax, when analyzing LocalFunctionStatementSyntax.

Fixes the CallActivityAsync piece of recognizing FunctionNames can be constants in FunctionAnalyzers.

Fixes a bug with MethodAnalyzer that causes a StackOverflowException when analyzing a recursive method.

### CODE REVIEW

File: src/WebJobs.Extensions.DurableTask.Analyzers/SyntaxNodeUtils.cs [hunk 1]
```diff
@@ -157,23 +158,48 @@ internal static bool TryGetFunctionNameAndNode(SemanticModel semanticModel, Synt
...
-            var stringLiteralExpression = attributeArgument.ChildNodes().Where(x => x.IsKind(SyntaxKind.StringLiteralExpression)).FirstOrDefault();
-            if (stringLiteralExpression != null)
+            if (TryGetStringFunctionName(node, out functionName))
             {
-                var stringLiteralToken = stringLiteralExpression.ChildTokens().Where(x => x.IsKind(SyntaxKind.StringLiteralToken)).FirstOrDefault();
-                if (stringLiteralToken != null)
+                return true;
+            }
+
+            if (TryGetNameOfFunctionName(node, out functionName))
```
Comment (ConnorMcMahon) [inline src/WebJobs.Extensions.DurableTask.Analyzers/SyntaxNodeUtils.cs:168]: At initial glance, this name is very confusing. I got it eventually, and I get the naming convention you used to derive it, but I think we may need to stir this up a bit to make it a bit less confusing.

Consider `TryGetFunctionNameInNameOfOperator`. It's more verbose, but I think it's a bit more clear. It's up to you if you want to change the other method names to match (i.e. `TryGetFunctionNameInStringLiteral` and `TryGetFunctionNameInConstant`).

Comment (amdeel) [reply src/WebJobs.Extensions.DurableTask.Analyzers/SyntaxNodeUtils.cs:168]: I like this suggestion, thanks!
