### PR TITLE
Expose OOP invocation errors

### LINKED ISSUE #2595: Problems with unhandled exception in Orchestrations, .net 7 isolated mode
Hi.
I'm running a function app v4 using .net 7 in isolated mode on a App Service Plan (S1) using Linux. My funciton app is the only app on this plan.
The problem I have is unhandled exception is disregarded. My orchestrations functions is completed with a Success state, and the unhandled exception is not logged to Application Insights log, exception table.
I have created a small function to isolate the problem. 
Both the functions TestOrchestrator and TestOrchestrator2 are completed with as a Success state.
The exceptions “TestOrchestrator2 failure” and “Stop further processing error” are not logged in Application Insights.
The Activity function DoSomeBusinessStuff is completed with a Failed state. 
The error “Failed to do the business stuff” is logged.
Also the Trace does not include the “_logger.LogInformation("Is this logged?");” from TestOrcestrator.
Meaning the unhandled exception occurs but is disregarded by the Orchestration functions.
According to the [documentation](https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-error-handling?tabs=csharp-isolated), this should not happen. Exception should have bin logged and the functions should complete with a Failed state. 
So why am I seeing different result?
What am I doing wrong?

`public class TestIsolatedError
{
    private readonly ILogger _logger;

    public TestIsolatedError(ILoggerFactory loggerFactory)
    {
        _logger = loggerFactory.CreateLogger<TestIsolatedError>();
    }

    [Function("TestIsolatedError")]
    public async Task<HttpResponseData> Run([HttpTrigger(AuthorizationLevel.Function, "get", "post")] HttpRequestData req,
        [DurableClient] DurableTaskClient client,
        CancellationToken cancellationToken)
    {
        _logger.LogInformation("C# HTTP trigger function processed a request.");

        await client.ScheduleNewOrchestrationInstanceAsync(nameof(TestOrchestrator), cancellationToken);
        await client.ScheduleNewOrchestrationInstanceAsync(nameof(TestOrchestrator2), cancellationToken);
        var response = req.CreateResponse(HttpStatusCode.OK);
        response.Headers.Add("Content-Type", "text/plain; charset=utf-8");
        response.WriteString("Welcome to Azure Functions!");
        return response;
    }

    [Function(nameof(TestOrchestrator2))]
    public async Task TestOrchestrator2([OrchestrationTrigger] TaskOrchestrationContext context)
    {
        _logger.LogInformation("Starting orchestration TestOrchestrator2");
        //The following exception is not logged.
        //This function is marked as completed successfully, how?
        throw new Exception("TestOrchestrator2 failure"); 
        //unreachable code, just to test.
        _logger.LogInformation("Is this logged?");
    }

    [Function(nameof(TestOrchestrator))]
    public async Task TestOrchestrator([OrchestrationTrigger] TaskOrchestrationContext context,
        CancellationToken cancellationToken)
    {

        _logger.LogInformation("Starting orchestration TestOrchestrator");            
        var options = TaskOptions.FromRetryPolicy(new RetryPolicy(maxNumberOfAttempts: 2, firstRetryInterval: TimeSpan.FromMinutes(1)));
        try
        {
            await context.CallActivityAsync(nameof(DoSomeBusinessStuff), options);
        }
        catch (TaskFailedException ex)
        {
            _logger.LogError(ex, "failed to execute business logic");
            throw new Exception("Stop further processing error", ex); //This exception is not logged.
        }
        //this is not logged. This orchestration is marked as sucessfull, why is this not logged?
        _logger.LogInformation("Is this logged?");
    }

    [Function(nameof(DoSomeBusinessStuff))]
    public async Task DoSomeBusinessStuff([ActivityTrigger] FunctionContext executionContext)
    {
        _logger.LogInformation("Starting doing som business stuff");
        //remove warning.
        await Task.Delay(1);
        // do some async business stuff
        throw new Exception("Failed to do the bussiness stuff");
    }
}
`

### PR DESCRIPTION
**Pull request by jviau**
This PR fixes an issue with failed orchestrations and entities not showing up as "failed" in telemetry.

### Issue describing the changes in this PR

resolves #2595

### Pull request checklist

* [x] My changes **do not** require documentation changes
    * [ ] Otherwise: Documentation PR is ready to merge and referenced in `pending_docs.md`
* [ ] My changes **should not** be added to the release notes for the next release
    * [x] Otherwise: I've added my notes to `release_notes.md`
* [x] My changes **do not** need to be backported to a previous version
    * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [ ] I have added all required tests (Unit tests, E2E tests)
* [x] My changes **do not** require any extra work to be leveraged by OutOfProc SDKs
    * [ ] Otherwise: That work is being tracked here: #issue_or_pr_in_each_sdk
* [x] My changes **do not** change the version of the WebJobs.Extensions.DurableTask package
    * [ ] Otherwise: major or minor version updates are reflected in `/src/Worker.Extensions.DurableTask/AssemblyInfo.cs`
* [x] My changes **do not** add EventIds to our EventSource logs
    * [ ] Otherwise: Ensure the EventIds are within the supported range in our existing Windows infrastructure. You may validate this with a deployed app's telemetry. You may also extend the range by completing a PR such as [this one](https://msazure.visualstudio.com/One/_git/AAPT-Antares-Websites/pullrequest/7463263?_a=files).
* [x] My changes **should** be added to v3.x branch.
    * [ ] Otherwise: This change only applies to Durable Functions v2.x and **will not** be merged to branch v3.x.

### CODE REVIEW

File: src/WebJobs.Extensions.DurableTask/ContextImplementations/RemoteEntityContext.cs [hunk 1]
```diff
@@ -20,9 +17,41 @@ public RemoteEntityContext(EntityBatchRequest batchRequest)
...
+
+            List<Exception>? errors = null;
+            if (this.Result.Results is not null)
+            {
+                foreach (OperationResult result in this.Result.Results)
+                {
+                    if (result.FailureDetails is { } failure)
+                    {
+                        errors ??= new List<Exception>();
+                        errors.Add(new OrchestrationFailureException(failure.ErrorMessage));
```
Comment (jviau) [inline src/WebJobs.Extensions.DurableTask/ContextImplementations/RemoteEntityContext.cs:46]: Need to create a new exception type, doesn't appear to be one in DurableTask.Core to reuse

File: src/WebJobs.Extensions.DurableTask/ContextImplementations/RemoteEntityContext.cs [hunk 2]
```diff
@@ -20,9 +19,40 @@ public RemoteEntityContext(EntityBatchRequest batchRequest)
...
+                        errors.Add(new EntityFailureException(failure.ErrorMessage));
+                    }
+                }
+            }
+
+            if (errors is not null)
+            {
+                throw errors.Count == 1 ? errors[0] : new AggregateException(errors);
+            }
+        }
```
Comment (davidmrdavid) [inline src/WebJobs.Extensions.DurableTask/ContextImplementations/RemoteEntityContext.cs:56]: this method throws me off. It's called "Ensure success" but it collects failures. Can you tell me more about this? Maybe add some comments.

**Review by davidmrdavid — COMMENTED** [review]
Some comments

File: src/WebJobs.Extensions.DurableTask/ContextImplementations/RemoteEntityContext.cs [hunk 3]
```diff
@@ -20,9 +19,40 @@ public RemoteEntityContext(EntityBatchRequest batchRequest)
         }
 
         [JsonProperty("request")]
-        public EntityBatchRequest Request { get; private set; }
+        internal EntityBatchRequest Request { get; private set; }
```
[the remark this answers is not in the document]
Comment (jviau) [reply src/WebJobs.Extensions.DurableTask/ContextImplementations/RemoteEntityContext.cs:23]: The type itself is `internal`. I just changed it for consistency with other properties.

File: src/WebJobs.Extensions.DurableTask/ContextImplementations/RemoteEntityContext.cs (hunk 2 above)
Comment (jviau) [reply src/WebJobs.Extensions.DurableTask/ContextImplementations/RemoteEntityContext.cs:56]: Inspired by https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpresponsemessage.ensuresuccessstatuscode?view=net-7.0. It "ensures success" because if it is successfull it will _not_ throw.

I'll switch to `ThrowIfFailed` to be clearer

**Review by davidmrdavid — APPROVED** [review]
Approved conditional on renaming `EnsureSuccess` to `ThrowIfFailed`
