### PR TITLE
Analyzer: Fixed NullReferenceException in FuncitonAnalyzer

### LINKED ISSUE #999: NullReferenceException in analyzer for CallActivityAsync
### Description
The following code snippet causes a `NullReferenceException` in the Durable Functions Roslyn analyzer:

```csharp
string[] dataFiles = await ctx.CallActivityAsync<string[]>("GetDataFiles", (object)null);
```

### Expected behavior
The analyzer should never have a `NullReferenceException`.

### Actual behavior
Here is the warning message:
```
Warning	AD0001	Analyzer 'Microsoft.Azure.WebJobs.Extensions.DurableTask.Analyzers.FunctionAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.	DFPerfScenarios		1	Active	Analyzer 'Microsoft.Azure.WebJobs.Extensions.DurableTask.Analyzers.FunctionAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: DFPerfScenarios
SyntaxTree: C:\Users\cgillum\Downloads\DFPerfScenarios\DFPerfScenarios\MapReduceTripData.cs
SyntaxNode: ctx.CallActivityAsync<string[]> ... [InvocationExpressionSyntax]@[843..904) (25,30)-(25,91)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.Analyzers.FunctionAnalyzer.GetQualifiedTypeName(ITypeSymbol typeInfo)
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.Analyzers.FunctionAnalyzer.FindActivityCalls(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__53`1.<ExecuteSyntaxNodeAction>b__53_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
```

### Known workarounds
I couldn't figure out how to make this warning go away. :(

### App Details
- **Analyzer version**: v0.1.1
- **Durable Functions extension version**: 2.0.0-beta3
- **Azure Functions runtime version (1.0 or 2.0)**: 2.0

### PR DESCRIPTION
**Pull request by amdeel**
Fixed FunctionAnalyzer from throwing a NullReferenceException.

This PR also refactors some of the code in FunctionAnalyzer and some of the classes that use similar methods.

resolves #999

### CODE REVIEW

File: src/WebJobs.Extensions.DurableTask.Analyzers/SyntaxNodeUtils.cs [hunk 1]
```diff
@@ -46,6 +47,56 @@ public static bool IsInsideOrchestrator(SyntaxNode node)
 
             return false;
         }
+        
+        public static bool IsMarkedDeterministic(SyntaxNode node)
```
Comment (cgillum) [inline src/WebJobs.Extensions.DurableTask.Analyzers/SyntaxNodeUtils.cs]: Tip: C# allows you to shrink this down to a one-line expression, like this:

```csharp
public static bool IsMarkedDeterministic(SyntaxNode node) => TryGetDeterministicAttribute(node, out _);
```

File: src/WebJobs.Extensions.DurableTask.Analyzers/SyntaxNodeUtils.cs [hunk 2]
```diff
@@ -46,6 +47,56 @@ public static bool IsInsideOrchestrator(SyntaxNode node)
...
+            }
+            return false;
+        }
+
+
+        public static bool TryGetDeterministicAttribute(SyntaxNode node, out SyntaxNode deterministicAttribute)
+        {
+            if (TryGetMethodDeclaration(node, out SyntaxNode methodDeclaration))
+            {
+                var IEnumeratorAttributeList = methodDeclaration.ChildNodes().Where(x => x.IsKind(SyntaxKind.AttributeList));
```
Comment (cgillum) [inline src/WebJobs.Extensions.DurableTask.Analyzers/SyntaxNodeUtils.cs]: nit: variable names should start with a lowercase letter. I simple name like `attributeLists` would be fine too.

File: src/WebJobs.Extensions.DurableTask.Analyzers/SyntaxNodeUtils.cs [hunk 3]
```diff
@@ -104,43 +166,11 @@ internal static bool TryGetFunctionAttribute(SyntaxNode attributeExpression, out
...
-
-        internal static bool TryGetParameterNodeNextToAttribute(AttributeSyntax attributeExpression, SyntaxNodeAnalysisContext context, out SyntaxNode inputType)
+        internal static bool TryGetParameterNodeNextToAttribute(SyntaxNodeAnalysisContext context, AttributeSyntax attributeExpression, out SyntaxNode inputType)
         {
             var parameter = attributeExpression.Parent.Parent;
-            var parameterTypeNamesEnumerable = parameter.ChildNodes().Where(x => x.IsKind(SyntaxKind.IdentifierName) || x.IsKind(SyntaxKind.PredefinedType));
+            var parameterTypeNamesEnumerable = parameter.ChildNodes().Where(x => x.IsKind(SyntaxKind.IdentifierName) || x.IsKind(SyntaxKind.PredefinedType) || x.IsKind(SyntaxKind.GenericName));
             if (parameterTypeNamesEnumerable.Any())
             {
                 inputType = parameterTypeNamesEnumerable.First();
```
Comment (cgillum) [inline src/WebJobs.Extensions.DurableTask.Analyzers/SyntaxNodeUtils.cs]: I see if a few places that you do an `IEnumerable<T>.Any()` statement followed by an `IEnumerable<T>.First()` statement. As a minor performance optimization, consider using `IEnumerable<T>.FirstOrDefault()` and then checking for null. This will avoid evaluating the enumerable multiple times.

File: src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/ActivityFunction/FunctionAnalyzer.cs [hunk 4]
```diff
@@ -56,115 +57,181 @@ private void RegisterAnalyzers(CompilationAnalysisContext context)
...
-                                ParameterType = typeName,
-                                ExpectedReturnType = returnTypeName,
-                                ExpectedReturnTypeNode = invocationExpression
-                            });
+                        return true;
                     }
                 }
             }
+
+            invocationExpression = null;
```
Comment (ConnorMcMahon) [inline src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/ActivityFunction/FunctionAnalyzer.cs]: This assignment is unnecessary, as it is already null at this point. In fact, you could replace the if-block with `return invocationExpresion != null`.

File: src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/ActivityFunction/FunctionAnalyzer.cs [hunk 5]
```diff
@@ -56,115 +57,181 @@ private void RegisterAnalyzers(CompilationAnalysisContext context)
...
+            return false;
         }
 
-        private string GetQualifiedTypeName(ITypeSymbol typeInfo)
+        private bool TryGetFunctionNameFromCallActivityInvocation(InvocationExpressionSyntax invocationExpression, out SyntaxNode functionNameNode)
+        {
+            functionNameNode = invocationExpression.ArgumentList.Arguments.FirstOrDefault();
+            if (functionNameNode != null)
```
Comment (ConnorMcMahon) [inline src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/ActivityFunction/FunctionAnalyzer.cs]: Similar comment about how this if-block is equivalent to `return functionNameNode != null`.

**Comment by oising** [comment]
I came to log a fresh issue, but this looks similar. Does this call stack look related?

```
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Warning	AD0001	Analyzer 'Microsoft.Azure.WebJobs.Extensions.DurableTask.Analyzers.FunctionAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.	Logient.Drms.Functions.Tests		1	Active	Analyzer 'Microsoft.Azure.WebJobs.Extensions.DurableTask.Analyzers.FunctionAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: (project)
SyntaxTree: (orchestratorfunc.cs)
SyntaxNode: x.CallActivityAsync<EventClippingEventRequest ... [InvocationExpressionSyntax]@[12649..12744) (258,28)-(258,123)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.Analyzers.FunctionAnalyzer.GetQualifiedTypeName(ITypeSymbol typeInfo)
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.Analyzers.FunctionAnalyzer.FindActivityCalls(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__55`1.<ExecuteSyntaxNodeAction>b__55_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
```

File: src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/ActivityFunction/FunctionAnalyzer.cs [hunk 6]
```diff
@@ -56,115 +57,181 @@ private void RegisterAnalyzers(CompilationAnalysisContext context)
...
+        private string GetReturnTypeNameFromCallActivityInvocation(SyntaxNodeAnalysisContext context, InvocationExpressionSyntax invocationExpression)
         {
-            var tupleunderlyingtype = (typeInfo as INamedTypeSymbol).TupleUnderlyingType;
-            if (tupleunderlyingtype != null)
+            if (SyntaxNodeUtils.TryGetTypeArgumentList((MemberAccessExpressionSyntax)invocationExpression.Expression, out SyntaxNode identifierNode))
             {
-                return $"Tuple<{string.Join(", ", tupleunderlyingtype.TypeArguments.Select(x => GetQualifiedTypeName(x)))}>";
+                var returnType = context.SemanticModel.GetTypeInfo(identifierNode).Type;
+                var returnTypeName = GetQualifiedTypeName(returnType);
+                if (returnTypeName != null)
```
Comment (ConnorMcMahon) [inline src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/ActivityFunction/FunctionAnalyzer.cs]: Is it even possible for `returnTypeName` to be null inside this block?

File: src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/ActivityFunction/FunctionAnalyzer.cs [hunk 7]
```diff
@@ -56,115 +57,181 @@ private void RegisterAnalyzers(CompilationAnalysisContext context)
...
+            return "System.Threading.Tasks.Task";
+        }
+
+        private SyntaxNode GetInputNodeFromCallActivityInvocation(InvocationExpressionSyntax invocationExpression)
+        {
+            var argumentNode = invocationExpression.ArgumentList.Arguments.LastOrDefault();
+            if (argumentNode != null)
             {
-                genericType = "<" + GetQualifiedTypeName(namedSymbol.TypeArguments.First()) + ">";
+                var inputNode = argumentNode.ChildNodes().First();
```
Comment (ConnorMcMahon) [inline src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/ActivityFunction/FunctionAnalyzer.cs]: `.First()` could theoretically throw an exception. I would recommend using `.FirstOrDefault()`.

**Comment by amdeel** [comment]
@oising It is related! This should be fixed with this PR. Thanks for coming to report the issue!

File: src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/ActivityFunction/FunctionAnalyzer.cs [hunk 8]
```diff
@@ -56,115 +57,181 @@ private void RegisterAnalyzers(CompilationAnalysisContext context)
...
-                                    ReturnType = GetQualifiedTypeName(returnType)
-                                });
-                            }
-                        }
+                        return $"System.Tuple<{string.Join(", ", tupleUnderlyingType.TypeArguments.Select(x => x.ToString()))}>";
                     }
+                    return typeInfo.ToString();
                 }
+
+                return typeInfo.ContainingNamespace?.ToString() + "." + typeInfo.Name?.ToString();
```
Comment (ConnorMcMahon) [inline src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/ActivityFunction/FunctionAnalyzer.cs]: If either `typeInfo.ContainingNamespace` or `typeInfo.Name` (and especially both) are null, I expect the name is going to look very strange. Is that OK?

File: src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/ActivityFunction/FunctionAnalyzer.cs [hunk 9]
```diff
@@ -56,115 +57,181 @@ private void RegisterAnalyzers(CompilationAnalysisContext context)
...
             }
+
+            return "";
```
Comment (ConnorMcMahon) [inline src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/ActivityFunction/FunctionAnalyzer.cs]: Maybe consider returning `"unknownType"`, as opposed to the empty string, as the empty string will both make error messages look weird, and are harder to interpret what it means.

File: src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/ActivityFunction/FunctionAnalyzer.cs [hunk 10]
```diff
@@ -56,115 +57,181 @@ private void RegisterAnalyzers(CompilationAnalysisContext context)
...
+        }
+
+        public void FindActivities(SyntaxNodeAnalysisContext context)
```
Comment (ConnorMcMahon) [inline src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/ActivityFunction/FunctionAnalyzer.cs]: Consider changing to the singular `FindActivity()`, since it doesn't look like it ever adds more than one. An even more descriptive name could be "AddActivityIfExists()`, but I am not sold on that.

File: src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/Entity/DispatchClassNameAnalyzer.cs [hunk 11]
```diff
@@ -40,17 +40,15 @@ private void AnalyzeDispatchEntityName(SyntaxNodeAnalysisContext context)
...
                 if (name.ToString().StartsWith("DispatchAsync"))
                 {
-                    if (TryGetTypeArgumentList(expression, out SyntaxNode typeArgumentList))
+                    if (SyntaxNodeUtils.TryGetTypeArgumentList(expression, out SyntaxNode identifierNode))
                     {
                         if (SyntaxNodeUtils.TryGetClassSymbol(expression, context.SemanticModel, out INamedTypeSymbol classSymbol))
                         {
                             var className = classSymbol.Name.ToString();
-
-                            //TypeArgumentList will always have a child node
```
Comment (ConnorMcMahon) [inline src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/Entity/DispatchClassNameAnalyzer.cs]: Was this not true?

File: src/WebJobs.Extensions.DurableTask.Analyzers/SyntaxNodeUtils.cs [hunk 12]
```diff
@@ -47,137 +48,138 @@ public static bool IsInsideOrchestrator(SyntaxNode node)
             return false;
         }
 
-        internal static bool TryGetClassSymbol(SyntaxNode node, SemanticModel semanticModel, out INamedTypeSymbol classSymbol)
+        public static bool IsMarkedDeterministic(SyntaxNode node) => TryGetDeterministicAttribute(node, out _);
+
+
+        public static bool TryGetDeterministicAttribute(SyntaxNode node, out SyntaxNode deterministicAttribute) => TryGetAttribute(node, "Deterministic", out deterministicAttribute);
```
Comment (ConnorMcMahon) [inline src/WebJobs.Extensions.DurableTask.Analyzers/SyntaxNodeUtils.cs]: This can probably be marked private, because I don't see us ever needing to get the actual `DeterministicAttribute`, we just want to know if it is present.

File: src/WebJobs.Extensions.DurableTask.Analyzers/SyntaxNodeUtils.cs [hunk 13]
```diff
@@ -47,137 +48,138 @@ public static bool IsInsideOrchestrator(SyntaxNode node)
...
-            while (!currNode.IsKind(SyntaxKind.ClassDeclaration))
+            if (TryGetMethodDeclaration(node, out SyntaxNode methodDeclaration))
             {
-                if (currNode.IsKind(SyntaxKind.CompilationUnit))
+                var attributeLists = methodDeclaration.ChildNodes().Where(x => x.IsKind(SyntaxKind.AttributeList));
+                foreach (var attributeList in attributeLists)
                 {
-                    classSymbol = null;
-                    return false;
+                    attribute = attributeList.ChildNodes().First();
```
Comment (ConnorMcMahon) [inline src/WebJobs.Extensions.DurableTask.Analyzers/SyntaxNodeUtils.cs]: Is `ChildNodes()` always guaranteed to have at least one element?

File: src/WebJobs.Extensions.DurableTask.Analyzers/SyntaxNodeUtils.cs (hunk 12 above)
Comment (amdeel) [reply src/WebJobs.Extensions.DurableTask.Analyzers/SyntaxNodeUtils.cs]: It's used in the CodeFixProviders actually. I noticed some of my methods are public and some are internal in SyntaxNodeUtils though. I should probably make them all the same (unless they're private).

File: src/WebJobs.Extensions.DurableTask.Analyzers/SyntaxNodeUtils.cs (hunk 13 above)
Comment (amdeel) [reply src/WebJobs.Extensions.DurableTask.Analyzers/SyntaxNodeUtils.cs]: Yes, I will add that as a comment

File: src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/Entity/DispatchClassNameAnalyzer.cs (hunk 11 above)
Comment (amdeel) [reply src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/Entity/DispatchClassNameAnalyzer.cs]: I moved that comment into a method I created in SyntaxNodeUtils called TryGetTypeArgumentList

File: src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/ActivityFunction/FunctionAnalyzer.cs [hunk 14]
```diff
@@ -152,16 +143,20 @@ private string GetQualifiedTypeName(ITypeSymbol typeInfo)
                     {
                         return $"System.Tuple<{string.Join(", ", tupleUnderlyingType.TypeArguments.Select(x => x.ToString()))}>";
                     }
+
                     return typeInfo.ToString();
                 }
 
-                return typeInfo.ContainingNamespace?.ToString() + "." + typeInfo.Name?.ToString();
+                if (!typeInfo.Name.Equals(""))
```
Comment (cgillum) [inline src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/ActivityFunction/FunctionAnalyzer.cs]: I recommend using `string.IsNullOrEmpty(typeInfo.Name)`.

File: src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/ActivityFunction/FunctionAnalyzer.cs [hunk 15]
```diff
@@ -152,16 +143,20 @@ private string GetQualifiedTypeName(ITypeSymbol typeInfo)
...
+                {
+                    return typeInfo.ContainingNamespace?.ToString() + "." + typeInfo.Name?.ToString();
```
Comment (cgillum) [inline src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/ActivityFunction/FunctionAnalyzer.cs]: the `?` in the`typeInfo.Name?.ToString()` expression is not needed since you already validated that `typeInfo.Name` is not null on line 150.

File: src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/ActivityFunction/FunctionAnalyzer.cs [hunk 16]
```diff
@@ -147,9 +147,9 @@ private string GetQualifiedTypeName(ITypeSymbol typeInfo)
                     return typeInfo.ToString();
                 }
 
-                if (!typeInfo.Name.Equals(""))
+                if (string.IsNullOrEmpty(typeInfo.Name))
```
Comment (cgillum) [inline src/WebJobs.Extensions.DurableTask.Analyzers/Analyzers/ActivityFunction/FunctionAnalyzer.cs]: I think the condition might be backwards. Should this be `if (!string.IsNullOrEmpty(typeInfo.Name))`?

File: src/WebJobs.Extensions.DurableTask.Analyzers/SyntaxNodeUtils.cs [hunk 17]
```diff
@@ -47,137 +48,139 @@ public static bool IsInsideOrchestrator(SyntaxNode node)
...
-            var parameterTypeNamesEnumerable = parameter.ChildNodes().Where(x => x.IsKind(SyntaxKind.IdentifierName) || x.IsKind(SyntaxKind.PredefinedType));
-            if (parameterTypeNamesEnumerable.Any())
+            inputType = parameter.ChildNodes().Where(x => x.IsKind(SyntaxKind.IdentifierName) || x.IsKind(SyntaxKind.PredefinedType) || x.IsKind(SyntaxKind.GenericName)).FirstOrDefault();
+            if (inputType != null)
             {
-                inputType = parameterTypeNamesEnumerable.First();
                 return true;
             }
 
             inputType = null;
```
Comment (ConnorMcMahon) [inline src/WebJobs.Extensions.DurableTask.Analyzers/SyntaxNodeUtils.cs]: nitpick: this is redundant.

Comment (amdeel) [reply src/WebJobs.Extensions.DurableTask.Analyzers/SyntaxNodeUtils.cs]: Good catch, worth a quick change
