### PR TITLE
Fixing Null Reference Bug in TaskEntityShim

### LINKED ISSUE #3167: NullReference exception in StartCallEntityAndEntityInvocationActivities
## Impact description
When using recent versions of Durable Functions with Durable entities, it is possible to get the following NullReferenceException from the extension: 

```
Function '<entity name> (Entity)' failed. TraceFlags: <flags>. Details: System.NullReferenceException: Object reference not set to an instance of an object.
at Microsoft.Azure.WebJobs.Extensions.DurableTask.TaskEntityShim.StartCallEntityAndEntityInvocationActivities(RequestMessage request, DateTimeOffset startTime) in /_/src/WebJobs.Extensions.DurableTask/Listener/TaskEntityShim.cs:line 759
at Microsoft.Azure.WebJobs.Extensions.DurableTask.TaskEntityShim.ProcessOperationRequestAsync(RequestMessage request) in /_/src/WebJobs.Extensions.DurableTask/Listener/TaskEntityShim.cs:line 458
at Microsoft.Azure.WebJobs.Extensions.DurableTask.TaskEntityShim.<>c__DisplayClass47_0.<<ExecuteBatch>g__ExecuteOperationsInBatch|0>d.MoveNext() in /_/src/WebJobs.Extensions.DurableTask/Listener/TaskEntityShim.cs:line 381
  --- End of stack trace from previous location ---
  at Microsoft.Azure.WebJobs.Extensions.DurableTask.TaskEntityShim.ExecuteBatch(CancellationToken onHostStopping) in /_/src/WebJobs.Extensions.DurableTask/Listener/TaskEntityShim.cs:line 392
  at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableTaskExtension.<>c__DisplayClass83_0.<<EntityMiddleware>b__0>d.MoveNext() in /_/src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs:line 939.
```

This error may result in function execution failures and/or process recycles.

## Who is impacted
Apps may be impacted if they meet the following criteria:

1. Distributed Tracing is _not_ enabled in host.json (see [Setting up distributed tracing](https://learn.microsoft.com/azure/azure-functions/durable/durable-functions-diagnostics?tabs=csharp-inproc#setting-up-distributed-tracing))
2. The app is using [Durable Entities](https://learn.microsoft.com/azure/azure-functions/durable/durable-functions-entities), and  [calls](https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-entities?tabs=function-based%2Cin-process%2Cpython-v2&pivots=csharp#example-orchestration-signals-and-calls-an-entity) an entity from an orchestration (apps that only signal entities should not be impacted)
3. The app is using .NET **in-process** (.NET Isolated is **not** impacted), Node.js, or Python
4. The app has one of the following dependencies:
    - Microsoft.Azure.WebJobs.Extensions.DurableTask **v3.2.0** or **v3.3.0**
    - Extension bundles **4.25.0**

## Known workarounds

The current recommended workaround is to enable distributed tracing v2, which was first introduced in v3.2.0. This can be done in host.json as follows:
```json
{
   "extensions": {
     "durableTask": {
         "tracing": {
            "DistributedTracingEnabled": true,
            "Version": "V2"
         }
     }
   }
 }
```

### PR DESCRIPTION
**Pull request by sophiatev**
There was a bug in my implementation of distributed tracing for entities leading to a null reference exception in the case that a `callEntityActivity` trace activity was not successfully created in `TaskEntityShim.StartCallEntityAndEntityInvocationActivities`. The null reference exception is thrown if `callEntityActivity` is null but we attempt to access its `Context` anyway. This PR fixes that bug by essentially changing this to a `callEntityActivity?.Context` call. 

Resolves #3167 

### Pull request checklist

* [ ] My changes **do not** require documentation changes
    * [ ] Otherwise: Documentation PR is ready to merge and referenced in `pending_docs.md`
* [ ] My changes **should not** be added to the release notes for the next release
    * [ ] Otherwise: I've added my notes to `release_notes.md`
* [ ] My changes **do not** need to be backported to a previous version
    * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [ ] I have added all required tests (Unit tests, E2E tests)
* [ ] My changes **do not** require any extra work to be leveraged by OutOfProc SDKs
    * [ ] Otherwise: That work is being tracked here: #issue_or_pr_in_each_sdk
* [ ] My changes **do not** change the version of the WebJobs.Extensions.DurableTask package
    * [ ] Otherwise: major or minor version updates are reflected in `/src/Worker.Extensions.DurableTask/AssemblyInfo.cs`
* [ ] My changes **do not** add EventIds to our EventSource logs
    * [ ] Otherwise: Ensure the EventIds are within the supported range in our existing Windows infrastructure. You may validate this with a deployed app's telemetry. You may also extend the range by completing a PR such as [this one](https://msazure.visualstudio.com/One/_git/AAPT-Antares-Websites/pullrequest/7463263?_a=files).
* [ ] My changes **should** be added to **v2.x** branch.
    * [ ] Otherwise: This change applies exclusively to WebJobs.Extensions.DurableTask v3.x. It will be retained only in the `dev` and `main` branches and will not be merged into the `v2.x` branch.

### CODE REVIEW

File: src/WebJobs.Extensions.DurableTask/Listener/TaskEntityShim.cs [hunk 1]
```diff
@@ -741,11 +741,13 @@ private async Task ExecuteOutOfProcBatch()
         {
             Activity processEntityInvocationActivity = null;
             Activity callEntityActivity = null;
+            ActivityContext? parentTraceContext;
```
Comment (cgillum) [inline src/WebJobs.Extensions.DurableTask/Listener/TaskEntityShim.cs]: I'm not quite understanding what we're changing in this file and need a little help. It looks like we're declaring two variables instead of one, but we're still only using one of those variables. Why was this change necessary?

Comment (sophiatev) [reply src/WebJobs.Extensions.DurableTask/Listener/TaskEntityShim.cs]: Yeah sorry, this is confusing. Basically, the problem is that I want this `parentTraceContext` to now be nullable so that I can assign to it from the `callEntityActivity?.Context` call. Previously, since I didn't need it to be nullable, I could just make it the `out` variable of the `ActivityContext.TryParse` call. But now, since it's nullable, I can't have it be the `out` variable of that call, so I have two variables - one is the `out` variable of the call and the other is this newly-nullable `parentTraceContext`. If the `TryParse` succeeds I just assign its result to `parentTraceContext`. Let me know if there's a better way to do this

(I also moved this `parentTraceContext` to be inside the `if` statement in the most recent commit, there was no reason it should have been outside of it)

Comment (andystaples) [reply src/WebJobs.Extensions.DurableTask/Listener/TaskEntityShim.cs]: I'm a little lost on this one too TBH - the code compiles without any changes to TaskEntityShim, right?. Passing a non-nullable object (parentTraceContext in this case) to a nullable parameter is valid in .NET, but not the other way around. Unless you were running into some error at runtime

Comment (sophiatev) [reply src/WebJobs.Extensions.DurableTask/Listener/TaskEntityShim.cs]: Ah yeah that's not the issue, the issue is that I'm trying to _assign_ a nullable value (`callEntityActivity?.Context`) to a non-nullable parameter `parentTraceContext`. Previously, the call was instead `callEntityActivity.Context`, which had a non-nullable result, and could be assigned to the non-nullable `parentTraceContext`. (But this is precisely what is causing the null reference exception, since `callEntityActivity` can in fact be null). So I had to change `parentTraceContext` to be nullable

Comment (andystaples) [reply src/WebJobs.Extensions.DurableTask/Listener/TaskEntityShim.cs]: Right yeah - I actually just enabled nullability for this solution and we have _a lot_ of dangerous null handling. 

I think you could do something like this here? Let me know if this makes sense - I'm not sure it's any more readable than what you have, though:
```csharp
parentTraceContext = callEntityActivity is not null ? callEntityActivity.Context : parentTraceContext;
```

Comment (andystaples) [reply src/WebJobs.Extensions.DurableTask/Listener/TaskEntityShim.cs]: Or better, 
```csharp
parentTraceContext = callEntityActivity?.Context ?? parentTraceContext;
```

Comment (sophiatev) [reply src/WebJobs.Extensions.DurableTask/Listener/TaskEntityShim.cs]: The problem is that I actually want `parentTraceContext` to hold a null value in the case that `callEntityActivity` is null. (This is because I want to then pass a null value to `StartActivityForProcessingEntityInvocation` for the parent trace context in that case). So unfortunately I can't use your suggestion (although I agree it's more readable).

**Review by andystaples — APPROVED** [review]
