### PR TITLE
Set custom DataConverter for OrchestrationContext in TaskOrchestrationShim

### LINKED ISSUE #1155: IMessageSerializerSettingsFactory not being used by TaskOrchestrationContext
The settings are being used correctly when triggering the orchestration.

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at DurableTask.Core.Serializing.JsonDataConverter.Deserialize(String data, Type objectType) in C:\source\durabletask\src\DurableTask.Core\Serializing\JsonDataConverter.cs:line 97
   at DurableTask.Core.TaskOrchestrationContext.<ScheduleTaskInternal>d__17.MoveNext() in C:\source\durabletask\src\DurableTask.Core\TaskOrchestrationContext.cs:line 104
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DurableTask.Core.TaskOrchestrationContext.<ScheduleTaskToWorker>d__16`1.MoveNext() in C:\source\durabletask\src\DurableTask.Core\TaskOrchestrationContext.cs:line 78
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DurableTask.Core.TaskOrchestrationContext.<ScheduleTask>d__15`1.MoveNext() in C:\source\durabletask\src\DurableTask.Core\TaskOrchestrationContext.cs:line 73
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableOrchestrationContext.<CallDurableTaskFunctionAsync>d__89`1.MoveNext() in d:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\ContextImplementations\DurableOrchestrationContext.cs:line 699
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MyFunctions.Orchestrator.<RunOrchestrator>d__7.MoveNext()

### Relevant source code snippets
```csharp
public TaskOrchestrationContext(OrchestrationInstance orchestrationInstance, TaskScheduler taskScheduler)
        {
            Utils.UnusedParameter(taskScheduler);

            this.openTasks = new Dictionary<int, OpenTaskInfo>();
            this.orchestratorActionsMap = new Dictionary<int, OrchestratorAction>();
            this.idCounter = 0;
            this.dataConverter = new JsonDataConverter();  // data converter is instantiated here
            OrchestrationInstance = orchestrationInstance;
            IsReplaying = false;
        }
// insert code snippet here
```

### App Details

- **Durable Functions extension version (e.g. v2.1.1)**:
- **Azure Functions runtime version 2.0**:
- **C# (Visual Studio 2019)**:

- **Timeframe issue observed**:
- **Function App name**:
- **Function name(s)**:
- **Azure region**:
- **Orchestration instance ID(s)**:
- **Azure storage account name**:

> If you don't want to share your Function App or storage account name GitHub, please at least share the orchestration instance ID. Otherwise it's extremely difficult to look up information.

### PR DESCRIPTION
**Pull request by amdeel**
related to https://github.com/Azure/durabletask/pull/376

resolves #1155

### CODE REVIEW

**Comment by amdeel** [comment]
I did manual testing for this to ensure custom serialization worked with activities. I also tested CallHttpAsync manually.

File: src/WebJobs.Extensions.DurableTask/Options/DurableTaskOptions.cs [hunk 1]
```diff
@@ -23,7 +23,7 @@ public class DurableTaskOptions
         /// <summary>
         /// Settings used for Durable HTTP functionality.
         /// </summary>
-        public HttpOptions HttpSettings { get; set; }
+        public HttpOptions HttpSettings { get; set; } = new HttpOptions();
```
Comment (amdeel) [inline src/WebJobs.Extensions.DurableTask/Options/DurableTaskOptions.cs]: I ran into a NullReferenceException in my CallHttpAsync manual test. HttpOptions was never given a value. This fixes that bug that I found.

File: test/Common/DurableHttpTests.cs [hunk 2]
```diff
@@ -892,7 +892,7 @@ private static bool UriContainsGivenString(HttpRequestMessage req, string uriEnd
         /// End-to-end test which checks if the CallHttpAsync Orchestrator returns an OK (200) status code
         /// when a Bearer Token is added to the DurableHttpRequest object.
         /// </summary>
-        [Theory]
+        // [Theory]
```
Comment (ConnorMcMahon) [inline test/Common/DurableHttpTests.cs]: Let's uncomment out all of these tests.

File: src/WebJobs.Extensions.DurableTask/Listener/TaskOrchestrationShim.cs [hunk 3]
```diff
@@ -53,6 +53,7 @@ public override async Task<string> Execute(OrchestrationContext innerContext, st
                 throw new InvalidOperationException($"The {nameof(this.FunctionInvocationCallback)} has not been assigned!");
             }
 
+            innerContext.DataConverter = this.dataConverter;
```
Comment (ConnorMcMahon) [inline src/WebJobs.Extensions.DurableTask/Listener/TaskOrchestrationShim.cs]: I understand that our `MessagePayloadDataConverter` uses the message serialization settings, but I think I would rather be explicit and use `this.dataConverter.MessageConverter`. That way, when we add better support for error serialization in DurableTask.Core, our logic is a bit more clear.

File: src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj [hunk 4]
```diff
@@ -63,6 +63,8 @@
   </ItemGroup>
 
   <ItemGroup>
+    <PackageReference Include="Microsoft.Azure.DurableTask.AzureStorage" Version="1.7.4" />
```
Comment (ConnorMcMahon) [inline src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj]: small nit: I think the reason we had two separate `<ItemGroup>` sections was because one has all of the private assets (i.e. only used for dev purpose) and the other has our actual dependencies. I think we should move these dependencies back to the other `<ItemGroup>` exception with the rest of our real dependencies.

File: src/WebJobs.Extensions.DurableTask/DurableHttpRequest.cs [hunk 5]
```diff
@@ -169,7 +169,8 @@ public override void WriteJson(JsonWriter writer, object value, JsonSerializer s
                 }
                 else
                 {
-                    // Don't know how to serialize this - use default behavior
+                    // Don't know how to serialize this - use default behavior, forcing TypeNameHandling.Objects to correctly serialize ITokenSource
+                    serializer.TypeNameHandling = TypeNameHandling.Objects;
```
Comment (ConnorMcMahon) [inline src/WebJobs.Extensions.DurableTask/DurableHttpRequest.cs]: This serializer might be reused later (not sure about how it works internally with Newtonsoft. Might be safer to store the current value of `serializer.TypeNameHandling` before we assign it to `TypeNameHandling.Objects`, sot that after calling `serializer.Serialize(writer, value)` we can reassign it to it's old value.

Comment (amdeel) [reply src/WebJobs.Extensions.DurableTask/DurableHttpRequest.cs]: Isn't this a non-issue because the serializer is passed in as a parameter?

Comment (ConnorMcMahon) [reply src/WebJobs.Extensions.DurableTask/DurableHttpRequest.cs]: Newtonsoft manages that serializer passed in as a parameter. I am not positive, but the serializer they give us MAY be used in more than just this one place.

File: src/WebJobs.Extensions.DurableTask/DurableHttpRequest.cs [hunk 6]
```diff
@@ -169,8 +169,11 @@ public override void WriteJson(JsonWriter writer, object value, JsonSerializer s
                 }
                 else
                 {
-                    // Don't know how to serialize this - use default behavior
+                    // Don't know how to serialize this - use default behavior, forcing TypeNameHandling.Objects to correctly serialize ITokenSource
+                    var currTypeNameSetting = serializer.TypeNameHandling;
+                    serializer.TypeNameHandling = TypeNameHandling.Objects;
```
Comment (cgillum) [inline src/WebJobs.Extensions.DurableTask/DurableHttpRequest.cs]: I'm worried this could cause race conditions. If a shared serializer is passed into this method then we're changing the serialization behavior potentially for many different parts of the code. It's only temporary because we're changing it back, but it still seems pretty dangerous to do this and could make debugging serialization problems extremely difficult. A safer alternative would be to create a new serializer object (copying any settings that we think are relevant) and *not* modify the serializer passed in as an argument.

Comment (ConnorMcMahon) [reply src/WebJobs.Extensions.DurableTask/DurableHttpRequest.cs]: Since this was merged, I can clean this up in a quick PR.

Comment (amdeel) [reply src/WebJobs.Extensions.DurableTask/DurableHttpRequest.cs]: https://github.com/Azure/azure-functions-durable-extension/pull/1283
